In [193]:
import pandas as pd
import numpy as np
import boto3
import logging
from io import StringIO
from dotenv import load_dotenv
from pathlib import Path
import os
import polars as pl
from logging import Logger
import json
from chalice import Response
from datetime import datetime, timedelta
from unidecode import unidecode
import warnings
import gc
from functions_mo import (
calculate_volume_distribution_factor,
calculate_volume_distribution_blocks,
get_item_from_dynamodb, 
get_item_from_dynamodb_global, 
get_ssm_parameter,
object_to_dataframe,
group_by_month,
multiply_price,
multiply_by_month_promediado,
multiply_p_social,
total_cost,
total_cost_block,
calculate_promediados_factor,
group_by_type,
group_by_type_sum,
merge_factor_by_id,
multipy_factor_combined,
multiply_p_social_block,
multipy_factor_combined_100021,
standardize_column_dates,
vlookup_function,
)

In [194]:
#set up logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)
warnings.filterwarnings("ignore")

In [195]:
env_path = Path('C:/Users/Nata_/Documents/Etapa_1_proyecto/Simulador_mano_de_obra/mano_de_obra_agrovid/var.env')

load_dotenv(dotenv_path=env_path)
AWS_PROFILE = os.environ["aws_profile"]
SSM_PARAMETER_BUCKET_INPUT_FILES_NAME = os.environ['SSM_PARAMETER_BUCKET_INPUT_FILES_NAME']
SSM_PARAMETER_BUCKET_OUTPUT_FILES_NAME = os.environ['SSM_PARAMETER_BUCKET_OUTPUT_FILES_NAME']
REGION = os.environ['REGION']
SSM_PARAMETER_DYNAMODB_MODULE_CONFIG_NAME = os.environ['SSM_PARAMETER_DYNAMODB_MODULE_CONFIG_NAME']
SSM_PARAMETER_DYNAMODB_GLOBAL_MODULE_CONFIG_NAME = os.environ['SSM_PARAMETER_DYNAMODB_GLOBAL_MODULE_CONFIG_NAME']

### Función para despliegue

In [196]:
def materiales(event, context):
    modulo: str = "modulo_mano_de_obra"
    modulo_revenue: str = "modulo_ingresos"
    PROCESS_TYPE = "er_simulado"
    modulo_global_materiales = "nombre_finca"
    file_revenue: str = "volumen.csv"
    body = event
    # # 4. Body (usually JSON, but can be other formats)
    # if event.get("body"):
    #     body = event["body"]
    #     # Assuming the body is JSON
    #     body = json.loads(body)
    #     print("body_json", body)
    #     print("type body_json", type(body))
    
    session = boto3.Session(profile_name=AWS_PROFILE)

    s3_client = session.client('s3', region_name=REGION)
    ssm_client = session.client("ssm", region_name=REGION)
    dynamodb_client = boto3.resource("dynamodb", region_name=REGION)

    bucket_input_files = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_BUCKET_INPUT_FILES_NAME,
        logger=logger,
        ssm_client=ssm_client,
        with_decryption=True,
    )
    bucket_output_files = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_BUCKET_OUTPUT_FILES_NAME,
        logger=logger,
        ssm_client=ssm_client,
        with_decryption=True,
    )
    dynamodb_table_name_module_config = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_DYNAMODB_MODULE_CONFIG_NAME,
        logger=logger,
        ssm_client=ssm_client,
        with_decryption=True,
    )

    dynamodb_table_name_global_module_config = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_DYNAMODB_GLOBAL_MODULE_CONFIG_NAME,
        logger=logger,
        ssm_client=ssm_client,
        with_decryption=True,
    )
    logger.info(f"{dynamodb_table_name_module_config}")

    module_config = get_item_from_dynamodb(
        table_name=dynamodb_table_name_module_config,
        key={"module": modulo, "process_type": PROCESS_TYPE},
        logger=logger,
        dynamodb_client=dynamodb_client,
    )

    global_config_materiales = get_item_from_dynamodb_global(
        table_name=dynamodb_table_name_global_module_config,
        partition_key_value=modulo_global_materiales,
        logger=logger,
        dynamodb_client=dynamodb_client,
   )
    
    
    input_files_names: dict = module_config["input_file_names_mano_de_obra"]
    farm_order: dict = global_config_materiales["fincas"]

    # Descarga el archivo CSV desde S3
    
    map_with_dfs = {}
    current_date = datetime.now().strftime("%Y-%m-%d")
    partition = body.get("partition", current_date)

    volum_file = object_to_dataframe(
        s3_client=s3_client,
        bucket_name=bucket_input_files,
        folder_name=f"{PROCESS_TYPE}/{modulo_revenue}",
        partition=partition,
        file_name=file_revenue,
    )

    try:
        for key, file in input_files_names.items():
            df = object_to_dataframe(
                s3_client=s3_client,
                bucket_name=bucket_input_files,
                folder_name=f"{PROCESS_TYPE}/{modulo}",
                partition=partition,
                file_name=file,
            )
            logger.info(f"file_key: {file} read successfully")
            map_with_dfs[key] = df
        volum_distribution = map_with_dfs["volum_distribution"]
    except Exception as e:
        logger.error(
            f"Error reding file {file} from {bucket_input_files}: error detail:{e}"
        )
        return Response(
            status_code=500,
            body=json.dumps(
                {
                    "message": f"Error reding file {file} from {bucket_input_files}: error detail:{e}"
                }
            ),
        )

### Importar los archivos

In [197]:
modulo: str = "modulo_mano_de_obra"
PROCESS_TYPE = "er_simulado"
dynamo_global_materiales = "nombre_finca"
modulo_global: str = "archivos_comunes_global"

   
session = boto3.Session(profile_name=AWS_PROFILE)

s3_client = session.client("s3", region_name=REGION)
ssm_client = session.client("ssm", region_name=REGION)
dynamodb_client = session.resource("dynamodb", region_name=REGION)

bucket_input_files = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_BUCKET_INPUT_FILES_NAME,
        logger=logger,
        ssm_client=ssm_client,
        with_decryption=True,
    )
dynamodb_table_name_module_config = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_DYNAMODB_MODULE_CONFIG_NAME,
        logger=logger,
        ssm_client=ssm_client,
        with_decryption=True,
    )

dynamodb_table_name_global_module_config = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_DYNAMODB_GLOBAL_MODULE_CONFIG_NAME,
        ssm_client=ssm_client,
        logger=logger,
        with_decryption=True
    ) 
    
    
logger.info(f"{dynamodb_table_name_module_config}")

module_config = get_item_from_dynamodb(
        table_name=dynamodb_table_name_module_config,
        key={"module": modulo, "process_type": PROCESS_TYPE},
        logger=logger,
        dynamodb_client=dynamodb_client,
    )

module_global_config = get_item_from_dynamodb(
        table_name=dynamodb_table_name_module_config,
        key={"module": modulo_global, "process_type": PROCESS_TYPE},
        logger=logger,
        dynamodb_client=dynamodb_client,)


global_config_materiales = get_item_from_dynamodb_global(
        table_name=dynamodb_table_name_global_module_config,
        partition_key_value=dynamo_global_materiales,
        logger=logger,
        dynamodb_client=dynamodb_client,
   )
 

input_files_names: dict = module_config["input_file_names_mo"]
input_global_file_names: dict = module_global_config["input_file_names_global"]
farm_order: dict = global_config_materiales["fincas"]

    # Descarga el archivo CSV desde S3
map_with_dfs = {}
current_date = datetime.now().strftime("%Y-%m-%d")
partition = "2025-02-19"

#extraer los archivos del modulo global
try:
    for key, file in input_global_file_names.items():
        df = object_to_dataframe(
            s3_client=s3_client,
            bucket_name=bucket_input_files,
            folder_name=f"{PROCESS_TYPE}/{modulo_global}",
            partition=partition,
            file_name=file,
        )

        logger.info(f"file_key: {file} read successfully")
        map_with_dfs[key] = df
    volum_distribution = map_with_dfs["volum_distribution"]
    volum_file = map_with_dfs["volum_file"]
    sku = map_with_dfs["sku"]
    
except Exception as e:
    logger.error(
            f"Error reding file {file} from {bucket_input_files}: error detail:{e}"
    )
     

#extraer los archivos del modulo particular
try:
    for key, file in input_files_names.items():
        df = object_to_dataframe(
            s3_client=s3_client,
            bucket_name=bucket_input_files,
            folder_name=f"{PROCESS_TYPE}/{modulo}",
            partition=partition,
            file_name=file,
        )

        logger.info(f"file_key: {file} read successfully")
        map_with_dfs[key] = df
    cut_emp     = map_with_dfs["cut_emp"]
    promediado  = map_with_dfs["promediado"]
    revenue_sku = map_with_dfs["revenue_sku"]
    desect_ha   = map_with_dfs["desect_ha"]
    parcela_mo  = map_with_dfs["parcela_mo"]
    esquema_mo  = map_with_dfs["esquema_mo"]
    
except Exception as e:
    logger.error(
            f"Error reding file {file} from {bucket_input_files}: error detail:{e}"
    )

2025-07-14 20:49:36,495 - INFO - Found credentials in shared credentials file: ~/.aws/credentials

2025-07-14 20:49:37,298 - INFO - Parameter dev-bucket-upload-files-name retrieved successfully.
2025-07-14 20:49:37,414 - INFO - Parameter dev-dynamodb-table-name-module-config retrieved successfully.
2025-07-14 20:49:37,514 - INFO - Parameter dev-dynamodb-table-name-global-config retrieved successfully.
2025-07-14 20:49:37,514 - INFO - dev-module-config
2025-07-14 20:49:38,548 - INFO - file_key: sku.csv read successfully
2025-07-14 20:49:38,832 - INFO - file_key: volumen.csv read successfully
2025-07-14 20:49:38,939 - INFO - file_key: distribucion_volumen.csv read successfully
2025-07-14 20:49:39,231 - INFO - file_key: input_mo.csv read successfully
2025-07-14 20:49:39,332 - INFO - file_key: curvas_g.csv read successfully
2025-07-14 20:49:39,448 - INFO - file_key: corte_y_empaque.csv read successfully
2025-07-14 20:49:39,565 - INFO - file_key: desect_ha_mo.csv read successfully
2025-07-14 20:49:39,675 - INFO - file_key: parcela.csv read successfully
2025-07-14 20:49:39,781 - INFO - file_key: esquemas.csv read successfully

## Corte y empaque

### labor 100001

In [198]:
volum_file.columns = list(volum_file.columns[:3]) + [pd.to_datetime(col, dayfirst=True, errors='coerce') for col in volum_file.columns[3:]]

In [199]:
volum_distribution.columns = list(volum_distribution.columns[:1]) + [pd.to_datetime(col, dayfirst=True, errors='coerce') for col in volum_distribution.columns[1:]]

In [200]:
volum_file_subset = volum_file.iloc[:,3:]

In [201]:
group_data = group_by_month(volum_file_subset, volum_file)
month_columns = group_data.iloc[:, 2:].columns

2025-07-14 20:49:39,886 - INFO - Inicia la función agrupando por mes.
2025-07-14 20:49:39,889 - INFO - agrupando las columnas por mes y sumandolas.
2025-07-14 20:49:39,893 - INFO - Se realizó la agrupación con éxito.

In [202]:
volum_distribution_matrix = volum_distribution.iloc[:, 1:]
volum_file_matrix = volum_file[volum_file['CONCEPTO'] == 'CAJAS'].iloc[:, 3:]
volum_file_subset = volum_file[volum_file['CONCEPTO'] == 'CAJAS']

In [203]:
full_matrix = volum_file_subset.merge(cut_emp, on=['FINCA'], how='inner')
full_matrix_100001 = full_matrix[full_matrix['ID'] == 100001]
factor_100001 = full_matrix_100001.FACTOR.reset_index(drop=True)

In [204]:
quantity_100001 = calculate_volume_distribution_factor(volum_file_matrix, volum_distribution_matrix, volum_file_subset, month_columns, factor_100001)

2025-07-14 20:49:39,936 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-07-14 20:49:40,032 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [205]:
labor_100001 = multiply_price(quantity_100001, full_matrix_100001, 'FINCA', 'TARIFA', 'PROMEDIADO', month_columns)

2025-07-14 20:49:40,052 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:40,052 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:40,052 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:40,064 - INFO - Proceso completado exitosamente.

In [206]:
promediado

,Detalle,PROMEDIADO,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
0,LABORES ORDINARIAS,G01,0.224581,0.224581,0.224581,0.224581,0.224581,0.224581,0.224581,0.224581,0.224581,0.224581,0.224581,0.224581
1,LABORES COMPLEMENTARIAS,G02,0.191781,0.191781,0.191781,0.191781,0.191781,0.191781,0.191781,0.191781,0.191781,0.191781,0.191781,0.191781
2,CONTRATISTA,G03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,GENERAL,G04,0.251154,0.158846,0.335769,0.158846,0.251154,0.289616,0.251154,0.251154,0.197308,0.205000,0.251154,0.243462
4,GENERAL,G05,0.291154,0.198846,0.375769,0.198846,0.291154,0.329616,0.291154,0.291154,0.237308,0.245000,0.291154,0.283462
5,CORTE & EMPAQUE (4 DIAS),G06,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104
6,CORTE & EMPAQUE (5 DIAS),G07,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104
7,CORTE & EMPAQUE (6 DIAS),G08,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104
8,LABORES CULTURALES,G09,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104
9,NaN,G10,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104
10,NaN,G11,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104
11,NaN,G12,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104
12,NaN,G13,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104
13,NaN,G14,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104
14,NaN,G15,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104
15,NaN,G16,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104
16,NaN,G17,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104
17,NaN,G18,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104
18,NaN,G19,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104
19,NaN,G20,0.280796,0.153846,0.448167,0.153846,0.315438,0.353900,0.280796,0.315438,0.192308,0.234642,0.315438,0.273104

In [207]:
promediado_100001 = multiply_by_month_promediado(labor_100001, promediado, month_columns)

2025-07-14 20:49:40,128 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:40,131 - INFO - Proceso completado exitosamente

In [208]:
social_p_100001 = multiply_p_social(labor_100001, promediado_100001,full_matrix_100001, 'FINCA', 'PRESTACIONES', 'LABOR',month_columns)

2025-07-14 20:49:40,148 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:40,156 - INFO - Suma realizada con éxito.
2025-07-14 20:49:40,156 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:40,164 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:40,164 - INFO - Proceso completado exitosamente.

In [209]:
cost_100001 = total_cost(labor_100001, promediado_100001, social_p_100001, 'FINCA', 'LABOR', month_columns)

2025-07-14 20:49:40,184 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:40,197 - INFO - Suma realizada con éxito.
2025-07-14 20:49:40,197 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:40,205 - INFO - Proceso completado exitosamente.

In [210]:
"""del volum_file_matrix
del volum_file_subset
del full_matrix_100001
del factor_100001
del quantity_100001
del labor_100001
del promediado_100001
del social_p_100001
del cost_100001

gc.collect()"""

'del volum_file_matrix\ndel volum_file_subset\ndel full_matrix_100001\ndel factor_100001\ndel quantity_100001\ndel labor_100001\ndel promediado_100001\ndel social_p_100001\ndel cost_100001\n\ngc.collect()'

### labor 100002 -5

In [211]:

volum_distribution_matrix = volum_distribution.iloc[:, 1:]

volum_file_matrix_10002 = volum_file[volum_file['CONCEPTO'] == 'CORTADOS'].iloc[:, 3:]
volum_file_subset_10002 = volum_file[volum_file['CONCEPTO'] == 'CORTADOS']

full_matrix_100002 = volum_file_subset_10002.merge(cut_emp, on=['FINCA'], how='inner')
full_matrix_100002 = full_matrix[full_matrix['ID'] == 100002]
full_matrix_100003 = full_matrix[full_matrix['ID'] == 100003]
full_matrix_100004 = full_matrix[full_matrix['ID'] == 100004]
full_matrix_100005 = full_matrix[full_matrix['ID'] == 100005]

factor_100002 = full_matrix_100002.FACTOR.reset_index(drop=True)
factor_100003 = full_matrix_100003.FACTOR.reset_index(drop=True)
factor_100004 = full_matrix_100004.FACTOR.reset_index(drop=True)
factor_100005 = full_matrix_100005.FACTOR.reset_index(drop=True)

In [212]:
quantity_100002 = calculate_volume_distribution_factor(volum_file_matrix_10002, volum_distribution_matrix, volum_file_subset_10002, month_columns, factor_100002)

2025-07-14 20:49:40,271 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-07-14 20:49:40,364 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [213]:
quantity_100003 = calculate_volume_distribution_factor(volum_file_matrix_10002, 
                                                       volum_distribution_matrix, 
                                                       volum_file_subset_10002, month_columns, 
                                                       factor_100003)

2025-07-14 20:49:40,387 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-07-14 20:49:40,464 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [214]:
quantity_100004 = calculate_volume_distribution_factor(volum_file_matrix_10002, 
                                                       volum_distribution_matrix, 
                                                       volum_file_subset_10002, month_columns, 
                                                       factor_100004)

2025-07-14 20:49:40,481 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-07-14 20:49:40,581 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [215]:
quantity_100005 = calculate_volume_distribution_factor(volum_file_matrix_10002, 
                                                       volum_distribution_matrix, 
                                                       volum_file_subset_10002, month_columns, 
                                                       factor_100005)

2025-07-14 20:49:40,598 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-07-14 20:49:40,713 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [216]:
labor_100002 = multiply_price(quantity_100002, full_matrix_100002, 'FINCA', 'TARIFA', 'PROMEDIADO', month_columns)
labor_100003 = multiply_price(quantity_100003, full_matrix_100003, 'FINCA', 'TARIFA', 'PROMEDIADO', month_columns)
labor_100004 = multiply_price(quantity_100004, full_matrix_100004, 'FINCA', 'TARIFA', 'PROMEDIADO', month_columns)
labor_100005 = multiply_price(quantity_100005, full_matrix_100005, 'FINCA', 'TARIFA', 'PROMEDIADO', month_columns)

2025-07-14 20:49:40,736 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:40,736 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:40,736 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:40,736 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:40,736 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:40,747 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:40,751 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:40,751 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:40,751 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:40,751 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:40,751 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:40,751 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:40,764 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:40,764 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:40,764 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:40,764 - INFO - Proceso completado exitosamente.

In [217]:
promediado_100002 = multiply_by_month_promediado(labor_100002, promediado, month_columns)
promediado_100003 = multiply_by_month_promediado(labor_100003, promediado, month_columns)
promediado_100004 = multiply_by_month_promediado(labor_100004, promediado, month_columns)
promediado_100005 = multiply_by_month_promediado(labor_100005, promediado, month_columns)

2025-07-14 20:49:40,780 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:40,796 - INFO - Proceso completado exitosamente
2025-07-14 20:49:40,796 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:40,815 - INFO - Proceso completado exitosamente
2025-07-14 20:49:40,819 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:40,825 - INFO - Proceso completado exitosamente
2025-07-14 20:49:40,831 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:40,838 - INFO - Proceso completado exitosamente

In [218]:
social_p_100002 = multiply_p_social(labor_100002, 
                                    promediado_100002,full_matrix_100002, 
                                    'FINCA', 'PRESTACIONES', 
                                    'LABOR',month_columns)

social_p_100003 = multiply_p_social(labor_100003, 
                                    promediado_100003,full_matrix_100003, 
                                    'FINCA', 'PRESTACIONES', 
                                    'LABOR',month_columns)
social_p_100004 = multiply_p_social(labor_100004, 
                                    promediado_100004,full_matrix_100004, 
                                    'FINCA', 'PRESTACIONES', 
                                    'LABOR',month_columns)
social_p_100005 = multiply_p_social(labor_100005, 
                                    promediado_100005,full_matrix_100005, 
                                    'FINCA', 'PRESTACIONES', 
                                    'LABOR',month_columns)

2025-07-14 20:49:40,856 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:40,859 - INFO - Suma realizada con éxito.
2025-07-14 20:49:40,864 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:40,865 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:40,865 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:40,865 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:40,865 - INFO - Suma realizada con éxito.
2025-07-14 20:49:40,865 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:40,882 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:40,882 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:40,882 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:40,890 - INFO - Suma realizada con éxito.
2025-07-14 20:49:40,890 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:40,896 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:40,897 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:40,897 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:40,897 - INFO - Suma realizada con éxito.
2025-07-14 20:49:40,897 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:40,911 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:40,913 - INFO - Proceso completado exitosamente.

In [219]:
cost_100002 = total_cost(labor_100002, promediado_100002, social_p_100002, 'FINCA', 'LABOR', month_columns)
cost_100003 = total_cost(labor_100003, promediado_100003, social_p_100003, 'FINCA', 'LABOR', month_columns)
cost_100004 = total_cost(labor_100004, promediado_100004, social_p_100004, 'FINCA', 'LABOR', month_columns)
cost_100005 = total_cost(labor_100005, promediado_100005, social_p_100005, 'FINCA', 'LABOR', month_columns)

2025-07-14 20:49:40,937 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:40,937 - INFO - Suma realizada con éxito.
2025-07-14 20:49:40,937 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:40,948 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:40,948 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:40,957 - INFO - Suma realizada con éxito.
2025-07-14 20:49:40,957 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:40,961 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:40,961 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:40,965 - INFO - Suma realizada con éxito.
2025-07-14 20:49:40,965 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:40,965 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:40,965 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:40,978 - INFO - Suma realizada con éxito.
2025-07-14 20:49:40,980 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:40,981 - INFO - Proceso completado exitosamente.

In [220]:
"""del volum_file_matrix_10002
del volum_file_subset_10002

del full_matrix_100002
del full_matrix_100003
del full_matrix_100004
del full_matrix_100005

del factor_100002
del factor_100003
del factor_100004
del factor_100005

del quantity_100002
del quantity_100003
del quantity_100004
del quantity_100005

del labor_100002
del labor_100003
del labor_100004
del labor_100005

del promediado_100002
del promediado_100003
del promediado_100004
del promediado_100005

del social_p_100002
del social_p_100003
del social_p_100004
del social_p_100005

del cost_100002
del cost_100003
del cost_100004
del cost_100005

gc.collect()"""

'del volum_file_matrix_10002\ndel volum_file_subset_10002\n\ndel full_matrix_100002\ndel full_matrix_100003\ndel full_matrix_100004\ndel full_matrix_100005\n\ndel factor_100002\ndel factor_100003\ndel factor_100004\ndel factor_100005\n\ndel quantity_100002\ndel quantity_100003\ndel quantity_100004\ndel quantity_100005\n\ndel labor_100002\ndel labor_100003\ndel labor_100004\ndel labor_100005\n\ndel promediado_100002\ndel promediado_100003\ndel promediado_100004\ndel promediado_100005\n\ndel social_p_100002\ndel social_p_100003\ndel social_p_100004\ndel social_p_100005\n\ndel cost_100002\ndel cost_100003\ndel cost_100004\ndel cost_100005\n\ngc.collect()'

### labor promediados

In [221]:
full_matrix_promediados_100006 = full_matrix[full_matrix['ID'] == 100006]
full_matrix_promediados_1000023 = full_matrix[full_matrix['ID'] == 100023]
factor_promediados_100006 = full_matrix_promediados_100006.FACTOR.reset_index(drop=True)
factor_promediados_1000023 = full_matrix_promediados_1000023.FACTOR.reset_index(drop=True)
factor_concat = pd.concat([factor_promediados_100006, factor_promediados_1000023], ignore_index=True)

In [222]:
quantity_promediados = calculate_promediados_factor(volum_distribution_matrix, volum_file_subset, month_columns, factor_concat)

2025-07-14 20:49:41,034 - INFO - Iniciando el cálculo de la matriz de distribución de volumen con 92 factores.
2025-07-14 20:49:41,034 - INFO - Procesando el mes: 0
2025-07-14 20:49:41,047 - INFO - Procesando el mes: 1
2025-07-14 20:49:41,065 - INFO - Procesando el mes: 2
2025-07-14 20:49:41,081 - INFO - Procesando el mes: 3
2025-07-14 20:49:41,092 - INFO - Procesando el mes: 4
2025-07-14 20:49:41,098 - INFO - Procesando el mes: 5
2025-07-14 20:49:41,114 - INFO - Procesando el mes: 6
2025-07-14 20:49:41,133 - INFO - Procesando el mes: 7
2025-07-14 20:49:41,134 - INFO - Procesando el mes: 8
2025-07-14 20:49:41,159 - INFO - Procesando el mes: 9
2025-07-14 20:49:41,165 - INFO - Procesando el mes: 10
2025-07-14 20:49:41,181 - INFO - Procesando el mes: 11
2025-07-14 20:49:41,198 - INFO - Matriz de resultados generada.
2025-07-14 20:49:41,198 - INFO - Matriz de resultados transpuesta y columnas renombradas.
2025-07-14 20:49:41,198 - INFO - DataFrame final concatenado con los datos de volumen transformados.

In [223]:
quantity_promediados_100023 = quantity_promediados.iloc[46:, :]
quantity_promediados_100006 = quantity_promediados.iloc[0:46, :]

In [224]:
labor_promediados_100023 = multiply_price(quantity_promediados_100023, 
                                          full_matrix_promediados_1000023, 
                                          'FINCA', 'TARIFA', 'PROMEDIADO', 
                                          month_columns)

2025-07-14 20:49:41,238 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:41,242 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:41,253 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:41,253 - INFO - Proceso completado exitosamente.

In [225]:
labor_promediados_100006 = multiply_price(quantity_promediados_100006, 
                                          full_matrix_promediados_100006, 
                                          'FINCA', 'TARIFA', 'PROMEDIADO', 
                                          month_columns)

2025-07-14 20:49:41,273 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:41,273 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:41,281 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:41,281 - INFO - Proceso completado exitosamente.

In [226]:
promediado_100023 = multiply_by_month_promediado(labor_promediados_100023, promediado, month_columns)
promediado_100006 = multiply_by_month_promediado(labor_promediados_100006, promediado, month_columns)

2025-07-14 20:49:41,314 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']

2025-07-14 20:49:41,328 - INFO - Proceso completado exitosamente
2025-07-14 20:49:41,338 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:41,349 - INFO - Proceso completado exitosamente

In [227]:
social_promediado_100023 = multiply_p_social(labor_promediados_100023, 
                                    promediado_100023 ,full_matrix_promediados_1000023, 
                                    'FINCA', 'PRESTACIONES', 
                                    'LABOR',month_columns)

social_promediado_1000006 = multiply_p_social(labor_promediados_100006,
                                    promediado_100006 ,full_matrix_promediados_100006, 
                                    'FINCA', 'PRESTACIONES', 
                                    'LABOR',month_columns)

2025-07-14 20:49:41,377 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:41,385 - INFO - Suma realizada con éxito.
2025-07-14 20:49:41,386 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:41,391 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:41,393 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:41,393 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:41,398 - INFO - Suma realizada con éxito.
2025-07-14 20:49:41,398 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:41,405 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:41,405 - INFO - Proceso completado exitosamente.

In [228]:
cost_promediado_100023 = total_cost(labor_promediados_100023, promediado_100023, social_promediado_100023, 'FINCA', 'LABOR', month_columns)
cost_promediado_100006 = total_cost(labor_promediados_100006, promediado_100006, social_promediado_1000006, 'FINCA', 'LABOR', month_columns)

2025-07-14 20:49:41,416 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:41,423 - INFO - Suma realizada con éxito.
2025-07-14 20:49:41,429 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:41,430 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:41,430 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:41,430 - INFO - Suma realizada con éxito.
2025-07-14 20:49:41,430 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:41,443 - INFO - Proceso completado exitosamente.

### cantidades modulo ingreso

In [229]:
revenue_sku_subset = revenue_sku[revenue_sku['SKU']!= 'Exc-']
revenue_sku_subset.loc[:, 'Farm'] = revenue_sku_subset['Farm'].astype(str).apply(unidecode)

In [230]:
input_mo_join = pd.merge(revenue_sku_subset, sku[['SKU', 'TIPO']] ,how = 'left', on = 'SKU')
input_mo_join.rename(columns={'Farm':'FINCA'}, inplace=True)

In [231]:
mo_grouped_total = group_by_type(input_mo_join, farms=farm_order)

2025-07-14 20:49:41,483 - INFO - Iniciando limpieza de columnas TIPO y FINCA...
2025-07-14 20:49:41,483 - INFO - Renombrando columnas de fechas al tipo Timestamp (posición 3 a penúltima)...
2025-07-14 20:49:41,494 - INFO - Obteniendo valores únicos de TIPO...
2025-07-14 20:49:41,494 - INFO - Creando combinaciones TIPO-FINCA completas...
2025-07-14 20:49:41,494 - INFO - Agrupando por TIPO y FINCA...
2025-07-14 20:49:41,494 - INFO - Uniendo con combinaciones completas...
2025-07-14 20:49:41,494 - INFO - Rellenando NaNs con ceros...
2025-07-14 20:49:41,494 - INFO - Proceso de agrupación finalizado exitosamente.

In [232]:
mo_pre_100008 = merge_factor_by_id(100008, mo_grouped_total, cut_emp)
mo_pre_100008_final = multipy_factor_combined(mo_pre_100008, 'PRE')
mo_pre_100008_final_subset = mo_pre_100008_final.iloc[:,2:54]
full_matrix_100008 = full_matrix[full_matrix['ID'] == 100008]
factor_100008 = full_matrix_100008.FACTOR.reset_index(drop=True)

2025-07-14 20:49:41,522 - INFO - Filtrando por TIPO = PRE
2025-07-14 20:49:41,522 - INFO - Aplicando FACTOR a columnas numéricas...

In [233]:
mo_100009 = group_by_type_sum(input_mo_join, farms=farm_order, types_sum=['EDK', 'ESP'])
mo_100009_factor = merge_factor_by_id(100009, mo_100009, cut_emp)
mo_100009_final =  multipy_factor_combined(mo_100009_factor, 'EDK+ESP')
mo_100009_final_subset = mo_100009_final.iloc[:,2:54]

2025-07-14 20:49:41,552 - INFO - Iniciando limpieza de columnas TIPO y FINCA...
2025-07-14 20:49:41,552 - INFO - Obteniendo valores únicos de TIPO...
2025-07-14 20:49:41,552 - INFO - Creando combinaciones TIPO-FINCA completas...
2025-07-14 20:49:41,562 - INFO - Agrupando por TIPO y FINCA...
2025-07-14 20:49:41,562 - INFO - Uniendo con combinaciones completas...
2025-07-14 20:49:41,562 - INFO - Rellenando NaNs con ceros...
2025-07-14 20:49:41,562 - INFO - Sumando tipos especificados: ['EDK', 'ESP']
2025-07-14 20:49:41,562 - INFO - Agregando fila de suma de tipos al DataFrame final...
2025-07-14 20:49:41,562 - INFO - Proceso de agrupación y orden finalizado exitosamente.
2025-07-14 20:49:41,581 - INFO - Filtrando por TIPO = EDK+ESP
2025-07-14 20:49:41,581 - INFO - Aplicando FACTOR a columnas numéricas...

In [234]:
mo_100010 = group_by_type_sum(input_mo_join, farms=farm_order, types_sum=['ESP', 'MG'])
mo_100010_factor = merge_factor_by_id(100010, mo_100010, cut_emp)
mo_100010_final = multipy_factor_combined(mo_100010_factor, 'ESP+MG')
mo_100010_final_subset = mo_100010_final.iloc[:,2:54]

2025-07-14 20:49:41,600 - INFO - Iniciando limpieza de columnas TIPO y FINCA...
2025-07-14 20:49:41,606 - INFO - Obteniendo valores únicos de TIPO...
2025-07-14 20:49:41,606 - INFO - Creando combinaciones TIPO-FINCA completas...
2025-07-14 20:49:41,606 - INFO - Agrupando por TIPO y FINCA...
2025-07-14 20:49:41,612 - INFO - Uniendo con combinaciones completas...
2025-07-14 20:49:41,614 - INFO - Rellenando NaNs con ceros...
2025-07-14 20:49:41,617 - INFO - Sumando tipos especificados: ['ESP', 'MG']
2025-07-14 20:49:41,622 - INFO - Agregando fila de suma de tipos al DataFrame final...
2025-07-14 20:49:41,622 - INFO - Proceso de agrupación y orden finalizado exitosamente.
2025-07-14 20:49:41,626 - INFO - Filtrando por TIPO = ESP+MG
2025-07-14 20:49:41,628 - INFO - Aplicando FACTOR a columnas numéricas...

In [235]:
mo_100011_factor = merge_factor_by_id(100011, mo_grouped_total, cut_emp)
mo_100011_final = multipy_factor_combined(mo_100011_factor, 'PRE')
mo_100011_final_subset = mo_100011_final.iloc[:,2:54]

2025-07-14 20:49:41,646 - INFO - Filtrando por TIPO = PRE
2025-07-14 20:49:41,646 - INFO - Aplicando FACTOR a columnas numéricas...

In [236]:
mo_100012_factor = merge_factor_by_id(100012, mo_grouped_total, cut_emp)
mo_100012_final = multipy_factor_combined(mo_100012_factor, 'WT')
mo_100012_final_subset = mo_100012_final.iloc[:,2:54]

2025-07-14 20:49:41,685 - INFO - Filtrando por TIPO = WT
2025-07-14 20:49:41,685 - INFO - Aplicando FACTOR a columnas numéricas...

In [237]:
mo_100013_factor = merge_factor_by_id(100013, mo_grouped_total, cut_emp)
mo_100013_final = multipy_factor_combined(mo_100013_factor, 'MG')
mo_100013_final_subset = mo_100013_final.iloc[:,2:54]

2025-07-14 20:49:41,724 - INFO - Filtrando por TIPO = MG
2025-07-14 20:49:41,724 - INFO - Aplicando FACTOR a columnas numéricas...

In [238]:
mo_08_13_concat = pd.concat([mo_pre_100008_final, mo_100009_final, mo_100010_final, 
                                   mo_100011_final, mo_100012_final, mo_100013_final], axis = 0)
mo_08_13_concat_subset = mo_08_13_concat.iloc[:,2:54]

In [239]:
quantity_08_13 = calculate_volume_distribution_blocks(mo_08_13_concat_subset, volum_distribution_matrix, volum_file_subset, month_columns)

2025-07-14 20:49:41,763 - INFO - Iniciando cálculo de volumen por bloques de 46 filas.
2025-07-14 20:49:42,289 - INFO - Cálculo de matriz de volumen completado correctamente.

In [240]:
id_list = [100008,100009, 100010, 100011, 100012, 100013]
full_matrix_block = full_matrix[full_matrix['ID'].isin(id_list)]
full_matrix_block.loc[:, 'FINCA'] = full_matrix_block['FINCA'].astype(str).apply(unidecode) 
full_matrix_block_subset = full_matrix_block[['ID', 'FINCA', 'PROMEDIADO', 'TARIFA']]

In [241]:
# Convertimos la columna 'FINCA' a categoría con el orden deseado
full_matrix_block_subset['FINCA'] = pd.Categorical(
    full_matrix_block_subset['FINCA'],
    categories=farm_order,
    ordered=True
)

# Ordenamos por ID descendente y luego por FINCA según farm_order
full_matrix_block_subset_sorted = full_matrix_block_subset.sort_values(
    by=['ID', 'FINCA'],
    ascending=[True, True]  # ID descendente, FINCA según orden de categorías
)

In [242]:
labor_08_13_concat = pd.concat([quantity_08_13.reset_index(drop=True), 
                                   full_matrix_block_subset_sorted.reset_index(drop=True)], 
                                   axis = 1)

In [243]:
# Paso 1: Guardar una vez los valores originales de los meses
if f'original_{month_columns[0]}' not in labor_08_13_concat.columns:
    for col in month_columns:
        labor_08_13_concat[f'original_{col}'] = labor_08_13_concat[col]

# Paso 2: Multiplicar siempre desde los originales
for col in month_columns:
    labor_08_13_concat[col] = labor_08_13_concat[f'original_{col}'] * labor_08_13_concat['TARIFA']

In [244]:
labor_08_13_subset = labor_08_13_concat[['FINCA', 'PROMEDIADO'] + list(month_columns)]
labor_08_13_subset.columns = labor_08_13_subset.columns.astype(str).str.strip()

In [245]:
promediado_08_13 = multiply_by_month_promediado(labor_08_13_subset, promediado, month_columns)

2025-07-14 20:49:42,404 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:42,413 - INFO - Proceso completado exitosamente

In [246]:
# Convertimos la columna 'FINCA' a categoría con el orden deseado
full_matrix_block['FINCA'] = pd.Categorical(
    full_matrix_block['FINCA'],
    categories=farm_order,
    ordered=True
)

# Ordenamos por ID descendente y luego por FINCA según farm_order
full_matrix_block_sorted = full_matrix_block.sort_values(
    by=['ID', 'FINCA'],
    ascending=[True, True]  # ID descendente, FINCA según orden de categorías
).reset_index(drop = True)

In [247]:
full_matrix_block_sorted_social = full_matrix_block_sorted[['FINCA', 'PRESTACIONES', 'LABOR', 'ID']]
labor_08_13_social = pd.concat([labor_08_13_subset, full_matrix_block_sorted_social], axis = 1)

In [248]:
social_p_08_13 = multiply_p_social_block(labor_08_13_social, promediado_08_13,full_matrix_block_sorted_social,month_columns)

2025-07-14 20:49:42,467 - INFO - Inicia la función de suma y multiplicación con PRESTACIONES.
2025-07-14 20:49:42,478 - INFO - Suma realizada con éxito.
2025-07-14 20:49:42,490 - INFO - Multiplicación con PRESTACIONES completada.

In [249]:
labor_08_13_social_cost = labor_08_13_social.iloc[:, 1:]
cost_08_13 = total_cost_block(labor_08_13_social_cost, promediado_08_13, social_p_08_13, 'FINCA', 'LABOR', month_columns)

2025-07-14 20:49:42,503 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:42,511 - INFO - Suma realizada con éxito.
2025-07-14 20:49:42,511 - INFO - Realizando el merge sobre la columna FINCA y LABOR
2025-07-14 20:49:42,516 - INFO - Proceso completado exitosamente.

In [250]:
id_list_2 = [100014,100015, 100016, 100017, 100018, 100019]
full_matrix_14_19_id = full_matrix[full_matrix['ID'].isin(id_list_2)]

In [251]:
#este codigo se utiliza para hacer un bucle for sobre todos los id que se encuentran en la lista id_list_2 y su formula corresponde con 
#la función calculate_volume_distribution_factor idem para el resto de calculos de labores, promediados, y costo total
quantity_list = []

for id_value in id_list_2:
    factor_series = full_matrix_14_19_id[full_matrix_14_19_id['ID'] == id_value]['FACTOR'].reset_index(drop=True)

    quantity_df = calculate_volume_distribution_factor(
        volum_file_matrix,
        volum_distribution_matrix,
        volum_file_subset,
        month_columns,
        factor_series
    )

    quantity_df['ID'] = id_value  # Añades el ID para identificar luego
    quantity_list.append(quantity_df)

# Unir todos los quantity en un solo DataFrame
quantity_all_df = pd.concat(quantity_list, ignore_index=True)

2025-07-14 20:49:42,552 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-07-14 20:49:42,646 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.
2025-07-14 20:49:42,650 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-07-14 20:49:42,735 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.
2025-07-14 20:49:42,735 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-07-14 20:49:42,812 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.
2025-07-14 20:49:42,828 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-07-14 20:49:42,913 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.
2025-07-14 20:49:42,913 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-07-14 20:49:43,008 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.
2025-07-14 20:49:43,008 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-07-14 20:49:43,097 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [252]:
labor_list = []

for id_value in id_list_2:
    # Filtrar los datos que corresponden a ese ID
    quantity_df = quantity_all_df[quantity_all_df['ID'] == id_value].reset_index(drop=True)
    filtered_df = full_matrix_14_19_id[full_matrix_14_19_id['ID'] == id_value].reset_index(drop=True)

    labor_df = multiply_price(
        quantity_df,
        filtered_df,
        'FINCA',
        'TARIFA',
        'PROMEDIADO',
        month_columns
    )

    labor_df['ID'] = id_value
    labor_list.append(labor_df)

# Unir todos los resultados en un solo DataFrame
final_labor_df_14_19 = pd.concat(labor_list, ignore_index=True)

2025-07-14 20:49:43,112 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:43,112 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:43,118 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'ID', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:43,118 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,125 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:43,125 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:43,129 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'ID', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:43,131 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,131 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:43,131 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:43,131 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'ID', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:43,131 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,131 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:43,131 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:43,148 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'ID', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:43,148 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,148 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:43,148 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:43,157 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'ID', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:43,157 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,162 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:43,162 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:43,164 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'ID', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:43,164 - INFO - Proceso completado exitosamente.

In [253]:
promediado_results = []

for id_value in id_list_2:
    labor_df = final_labor_df_14_19[final_labor_df_14_19['ID'] == id_value].reset_index(drop=True)

    promediado_df = multiply_by_month_promediado(
        labor_df,
        promediado,
        month_columns
    )
    
    promediado_df['ID'] = id_value
    promediado_results.append(promediado_df)

# Concatenar en un solo DataFrame final
final_promediado_df_14_19 = pd.concat(promediado_results, ignore_index=True)

2025-07-14 20:49:43,196 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'ID', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:43,204 - INFO - Proceso completado exitosamente
2025-07-14 20:49:43,211 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'ID', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:43,214 - INFO - Proceso completado exitosamente
2025-07-14 20:49:43,223 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'ID', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:43,229 - INFO - Proceso completado exitosamente
2025-07-14 20:49:43,236 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'ID', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:43,243 - INFO - Proceso completado exitosamente
2025-07-14 20:49:43,245 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'ID', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:43,257 - INFO - Proceso completado exitosamente
2025-07-14 20:49:43,263 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'ID', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:43,268 - INFO - Proceso completado exitosamente

In [254]:
social_p_results = []

for id_value in id_list_2:
    labor_df = final_labor_df_14_19[final_labor_df_14_19['ID'] == id_value].reset_index(drop=True)
    promediado_df = final_promediado_df_14_19[final_promediado_df_14_19['ID'] == id_value].reset_index(drop=True)
    filtered_matrix = full_matrix_14_19_id[full_matrix_14_19_id['ID'] == id_value].reset_index(drop=True)

    social_df = multiply_p_social(
        labor_df,
        promediado_df,
        filtered_matrix,
        'FINCA',
        'PRESTACIONES',
        'LABOR',
        month_columns
    )
    
    social_df['ID'] = id_value
    social_p_results.append(social_df)

# Concatenar resultados en un solo DataFrame final
final_social_p_df_14_19 = pd.concat(social_p_results, ignore_index=True)

2025-07-14 20:49:43,285 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:43,297 - INFO - Suma realizada con éxito.
2025-07-14 20:49:43,297 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:43,303 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:43,303 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,303 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:43,317 - INFO - Suma realizada con éxito.
2025-07-14 20:49:43,317 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:43,324 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:43,324 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,328 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:43,335 - INFO - Suma realizada con éxito.
2025-07-14 20:49:43,337 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:43,342 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:43,344 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,347 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:43,354 - INFO - Suma realizada con éxito.
2025-07-14 20:49:43,355 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:43,360 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:43,361 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,364 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:43,370 - INFO - Suma realizada con éxito.
2025-07-14 20:49:43,370 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:43,378 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:43,378 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,381 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:43,387 - INFO - Suma realizada con éxito.
2025-07-14 20:49:43,387 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:43,393 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:43,393 - INFO - Proceso completado exitosamente.

In [255]:
cost_results = []

for id_value in id_list_2:
    labor_df = final_labor_df_14_19[final_labor_df_14_19['ID'] == id_value].reset_index(drop=True)
    promediado_df = final_promediado_df_14_19[final_promediado_df_14_19['ID'] == id_value].reset_index(drop=True)
    social_p_df = final_social_p_df_14_19[final_social_p_df_14_19['ID'] == id_value].reset_index(drop=True)

    cost_df = total_cost(
        labor_df,
        promediado_df,
        social_p_df,
        'FINCA',
        'LABOR',
        month_columns
    )
    
    cost_df['ID'] = id_value
    cost_results.append(cost_df)

# Concatenar resultados en un solo DataFrame final
final_cost_df_14_19 = pd.concat(cost_results, ignore_index=True)

2025-07-14 20:49:43,412 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:43,414 - INFO - Suma realizada con éxito.
2025-07-14 20:49:43,414 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:43,414 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,428 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:43,431 - INFO - Suma realizada con éxito.
2025-07-14 20:49:43,431 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:43,440 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,444 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:43,450 - INFO - Suma realizada con éxito.
2025-07-14 20:49:43,450 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:43,450 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,459 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:43,464 - INFO - Suma realizada con éxito.
2025-07-14 20:49:43,464 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:43,464 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,473 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:43,478 - INFO - Suma realizada con éxito.
2025-07-14 20:49:43,478 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:43,484 - INFO - Proceso completado exitosamente.
2025-07-14 20:49:43,484 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:43,494 - INFO - Suma realizada con éxito.
2025-07-14 20:49:43,494 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:43,498 - INFO - Proceso completado exitosamente.

In [256]:
volum_file_matrix_binaria = (volum_file_matrix > 0).astype(int)

In [257]:
full_matrix_100020 = full_matrix[full_matrix['ID'] == 100020]
factor_100020 = full_matrix_100020.FACTOR.reset_index(drop=True)

In [258]:
quantity_df_100020 = calculate_volume_distribution_factor(
        volum_file_matrix_binaria,
        volum_distribution_matrix,
        volum_file_subset,
        month_columns,
        factor_100020
    )

2025-07-14 20:49:43,583 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-07-14 20:49:43,680 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [259]:
labor_100020 = multiply_price(quantity_df_100020, 
                              full_matrix_100020, 
                              'FINCA', 'TARIFA', 'PROMEDIADO', 
                              month_columns)

2025-07-14 20:49:43,704 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:43,705 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:43,711 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:43,713 - INFO - Proceso completado exitosamente.

In [260]:
promediado_100020 = multiply_by_month_promediado(labor_100020, 
                                                 promediado, 
                                                 month_columns)

2025-07-14 20:49:43,731 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:43,731 - INFO - Proceso completado exitosamente

In [261]:
social_p_100020 = multiply_p_social(labor_100020, 
                                    promediado_100020,
                                    full_matrix_100020,
                                    'FINCA', 'PRESTACIONES', 'LABOR',
                                    month_columns)

2025-07-14 20:49:43,748 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:43,748 - INFO - Suma realizada con éxito.
2025-07-14 20:49:43,748 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:43,763 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:43,763 - INFO - Proceso completado exitosamente.

In [262]:
cost_100020 = total_cost(labor_100020, 
                          promediado_100020, 
                          social_p_100020, 
                          'FINCA', 'LABOR', 
                          month_columns)

2025-07-14 20:49:43,782 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:43,782 - INFO - Suma realizada con éxito.
2025-07-14 20:49:43,782 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:43,798 - INFO - Proceso completado exitosamente.

In [263]:
mo_100009_final =  multipy_factor_combined(mo_100009_factor, 'EDK+ESP')

2025-07-14 20:49:43,815 - INFO - Filtrando por TIPO = EDK+ESP
2025-07-14 20:49:43,815 - INFO - Aplicando FACTOR a columnas numéricas...

In [264]:
mo_100021_factor = merge_factor_by_id(100021, mo_grouped_total, cut_emp)
mo_100021_mg = multipy_factor_combined_100021(mo_100021_factor, 'MG', 3)
mo_100021_edk = multipy_factor_combined_100021(mo_100021_factor, 'EDK',2)
mo_100021_mg_subset = mo_100021_mg.iloc[:,2:54].reset_index(drop=True)
mo_100021_edk_subset = mo_100021_edk.iloc[:,2:54].reset_index(drop=True)

2025-07-14 20:49:43,835 - INFO - Filtrando por TIPO = MG
2025-07-14 20:49:43,847 - INFO - Aplicando FACTOR a columnas numéricas...
2025-07-14 20:49:43,847 - INFO - Filtrando por TIPO = EDK
2025-07-14 20:49:43,847 - INFO - Aplicando FACTOR a columnas numéricas...

In [265]:
factor_100021 = full_matrix[full_matrix['ID'] == 100021].reset_index(drop = True).FACTOR
full_matrix_100021 = full_matrix[full_matrix['ID'] == 100021].reset_index(drop = True)
mg_plus_edk = pd.DataFrame()

for date in mo_100021_edk_subset.columns:
    mg_plus_edk[date] = mo_100021_mg_subset[date] + mo_100021_edk_subset[date]

In [266]:
quantity_mg_edk = calculate_volume_distribution_factor(
        mg_plus_edk,
        volum_distribution_matrix,
        volum_file_subset,
        month_columns,
        factor_100021
    )

2025-07-14 20:49:43,914 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-07-14 20:49:44,048 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [267]:
labor_100021 = multiply_price(
        quantity_mg_edk,
        full_matrix_100021,
        'FINCA',
        'TARIFA',
        'PROMEDIADO',
        month_columns
    )

2025-07-14 20:49:44,064 - INFO - Inicia la función para multiplicar los DataFrames.
2025-07-14 20:49:44,064 - INFO - Realizando el merge sobre la columna FINCA
2025-07-14 20:49:44,080 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-07-14 20:49:44,081 - INFO - Proceso completado exitosamente.

In [268]:

promediado_100021 = multiply_by_month_promediado(labor_100021,
                                          promediado, 
                                          month_columns
                                          )

2025-07-14 20:49:44,098 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-07-14 20:49:44,117 - INFO - Proceso completado exitosamente

In [269]:
social_100021 = multiply_p_social(labor_100021,
                                  promediado_100021,
                                  full_matrix_100021,
                                  'FINCA',
                                  'PRESTACIONES',
                                  'LABOR',
                                   month_columns)

2025-07-14 20:49:44,132 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:44,132 - INFO - Suma realizada con éxito.
2025-07-14 20:49:44,147 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:44,148 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-07-14 20:49:44,148 - INFO - Proceso completado exitosamente.

In [270]:
cost_100021 = total_cost(
        labor_100021,
        promediado_100021,
        social_100021,
        'FINCA',
        'LABOR',
        month_columns
    )

2025-07-14 20:49:44,165 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-07-14 20:49:44,165 - INFO - Suma realizada con éxito.
2025-07-14 20:49:44,165 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-07-14 20:49:44,182 - INFO - Proceso completado exitosamente.

### CONCATENAMOS TODOS LOS ID POR LABOR, PROMEDIADO, P SOCIALES Y COSTO

In [271]:
#labor 

total_labor_concat = pd.concat([labor_100001, labor_100002, labor_100003, labor_100004,
                                labor_100005, labor_promediados_100006, labor_promediados_100023, 
                                labor_08_13_concat, final_labor_df_14_19, labor_100020,
                                labor_100021], axis = 0)

#promediado

total_promediado_concat = pd.concat([promediado_100001, promediado_100002, promediado_100003,
                                     promediado_100004, promediado_100005, 
                                     promediado_100006, promediado_100023, promediado_08_13,
                                     final_promediado_df_14_19, promediado_100020,
                                     promediado_100021], axis=0)

In [272]:
#social
total_social_concat = pd.concat([social_p_100001, social_p_100002, social_p_100003,
                                 social_p_100004, social_p_100005, social_promediado_1000006, 
                                 social_promediado_100023, social_p_08_13, final_social_p_df_14_19,
                                 social_p_100020, social_100021])

In [273]:
#cost
total_cost_concat = pd.concat([cost_100001, cost_100002, cost_100003,
                               cost_100004, cost_100005, cost_promediado_100006, cost_promediado_100006,
                               cost_08_13, final_cost_df_14_19, cost_100020,
                               cost_100021])

## Parcela

In [274]:
ha = volum_file[volum_file['CONCEPTO'] == 'HA CULTIVABLE'].iloc[:, 3:].replace(0, np.nan).reset_index(drop = True)
emb = volum_file[volum_file['CONCEPTO'] == 'EMBOLSADOS'].iloc[:, 3:].reset_index(drop = True)
desect_ha_subset = desect_ha.iloc[:, 1:]

In [275]:
original_columns = desect_ha_subset.columns
columns_std  = pd.to_datetime(original_columns, errors = 'raise', dayfirst=True)
desect_ha_subset.columns = columns_std

In [276]:
desect_emb = (desect_ha_subset / ha) * emb *0.5

In [277]:
numerador = emb - desect_emb
denominador = ha - desect_ha_subset
denominador = denominador.replace(0, np.nan)
rac_ha = numerador.divide(denominador)
rac_ha = rac_ha.replace([np.inf, -np.inf], np.nan).fillna(0)
rac_ha[rac_ha < 0] = np.nan
rac_ha = rac_ha.fillna(0)

In [278]:
rac_ha_farms = pd.concat([rac_ha, desect_ha.FINCA], axis = 1)
rac_ha_farms_join = parcela_mo[parcela_mo['LABOR'] == 'PARCELA'][['FINCA', 'ESQUEMA']].merge(rac_ha_farms, on='FINCA', how='inner').iloc[:,1:]
schema_result = vlookup_function(rac_ha_farms_join, esquema_mo, 'VALOR')
schema_result_percent = vlookup_function(rac_ha_farms_join, esquema_mo, 'PORCENTAJE')

In [279]:
parcial_result = abs((desect_ha_subset - ha)).fillna(0)

In [280]:
q_result = parcial_result.multiply(parcela_mo[parcela_mo['LABOR'] == 'PARCELA'].VUELTAS, axis=0)
amount_reesult = (q_result * schema_result)

In [281]:

#(ha - desect_ha)/vueltas * schema_result

In [282]:
#AYUDANTE 
schema_result_std = standardize_column_dates(schema_result.iloc[:, 0:-1])
parcela_ay = parcela_mo[parcela_mo['LABOR']=='AYUDANTE']
parcela_plan = parcela_mo[parcela_mo['LABOR']=='PLANTILLA']
matrix_vtas = pd.DataFrame(np.repeat(parcela_ay['VUELTAS'].values[:, np.newaxis], len(ha.columns), axis=1),
                             index=ha.index, columns=ha.columns)
q_initial_result = ((ha - desect_ha_subset).divide(matrix_vtas.replace(0, np.nan))) * schema_result_percent
q_ay = q_initial_result.replace([np.inf, -np.inf], np.nan).fillna(0)

In [283]:
#PLANTILLA
matrix_vtas_plan = pd.DataFrame(np.repeat(parcela_plan['VUELTAS'].values[:, np.newaxis], len(ha.columns), axis=1),
                             index=ha.index, columns=ha.columns)
q_plan = desect_ha_subset.divide(matrix_vtas_plan.replace(0, np.nan)).fillna(0)

In [284]:
q_plan

,2024-01-06,2024-01-13,2024-01-20,2024-01-27,2024-02-03,2024-02-10,2024-02-17,2024-02-24,2024-03-02,2024-03-09,...,2024-10-26,2024-11-02,2024-11-09,2024-11-16,2024-11-23,2024-11-30,2024-12-07,2024-12-14,2024-12-21,2024-12-28
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,15.789474,15.789474,15.789474,15.789474,15.789474,15.789474,15.789474,15.789474,15.789474,15.789474,...,15.789474,15.789474,15.789474,15.789474,15.789474,15.789474,15.789474,15.789474,15.789474,15.789474
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,14.721053,14.721053,14.721053,14.721053,14.721053,14.721053,14.721053,14.721053,14.721053,14.721053,...,14.721053,14.721053,14.721053,14.721053,14.721053,14.721053,14.721053,14.721053,14.721053,14.721053
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,51.947368,51.947368,51.947368,51.947368,51.947368,51.947368,51.947368,51.947368,51.947368,51.947368,...,51.947368,51.947368,51.947368,51.947368,51.947368,51.947368,51.947368,51.947368,51.947368,51.947368
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,40.526316,40.526316,40.526316,40.526316,40.526316,40.526316,40.526316,40.526316,40.526316,40.526316,...,40.526316,40.526316,40.526316,40.526316,40.526316,40.526316,40.526316,40.526316,40.526316,40.526316
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,70.100000,70.100000,70.100000,70.100000,70.100000,70.100000,70.100000,70.100000,70.100000,70.100000,...,70.100000,70.100000,70.100000,70.100000,70.100000,70.100000,70.100000,70.100000,70.100000,70.100000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
27,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30,26.378947,26.378947,26.378947,26.378947,26.378947,26.378947,26.378947,26.378947,26.378947,26.378947,...,26.378947,26.378947,26.378947,26.378947,26.378947,26.378947,26.378947,26.378947,26.378947,26.378947
31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
32,12.105263,12.105263,12.105263,12.105263,12.105263,12.105263,12.105263,12.105263,12.105263,12.105263,...,12.105263,12.105263,12.105263,12.105263,12.105263,12.105263,12.105263,12.105263,12.105263,12.105263
33,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
34,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,...,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000
35,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
36,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
38,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
40,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
41,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
42,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
43,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
44,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
45,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000