In [2]:
import pandas as pd
import numpy as np
import boto3
import logging
from io import StringIO
from dotenv import load_dotenv
from pathlib import Path
import os
import polars as pl
from logging import Logger
import json
from chalice import Response
from datetime import datetime, timedelta
from unidecode import unidecode
import unicodedata
import warnings
import gc
import unicodedata
from functions_mo import (
calculate_volume_distribution_factor,
calculate_volume_distribution_blocks,
get_item_from_dynamodb, 
get_item_from_dynamodb_global, 
get_ssm_parameter,
object_to_dataframe,
group_by_month,
multiply_price,
multiply_by_month_promediado,
multiply_p_social,
total_cost,
total_cost_block,
calculate_promediados_factor,
group_by_type,
group_by_type_sum,
merge_factor_by_id,
multipy_factor_combined,
multiply_p_social_block,
multipy_factor_combined_100021,
standardize_column_dates,
vlookup_function,
social_p_parcela,
total_cost_parcela,
labores_ciclicas, 
farm_order_process,
reparar_codificacion, 
calculate_volume_distribution_blocks_ciclics,
multiply_months_by_price_ciclics,
ciclics_labor_calculation,
multiply_by_month_promediado_ciclics, 
multiply_p_social_block_ciclics, 
quantity_fijas,
quantity_other_labors,
quantity_other_labors_800008, 
build_factor_quantity
)

In [3]:
#set up logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)
warnings.filterwarnings("ignore")

In [4]:
env_path = Path('C:/Users/Nata_/Documents/Etapa_1_proyecto/Simulador_mano_de_obra/mano_de_obra_agrovid/var.env')

load_dotenv(dotenv_path=env_path)
AWS_PROFILE = os.environ["aws_profile"]
SSM_PARAMETER_BUCKET_INPUT_FILES_NAME = os.environ['SSM_PARAMETER_BUCKET_INPUT_FILES_NAME']
SSM_PARAMETER_BUCKET_OUTPUT_FILES_NAME = os.environ['SSM_PARAMETER_BUCKET_OUTPUT_FILES_NAME']
REGION = os.environ['REGION']
SSM_PARAMETER_DYNAMODB_MODULE_CONFIG_NAME = os.environ['SSM_PARAMETER_DYNAMODB_MODULE_CONFIG_NAME']
SSM_PARAMETER_DYNAMODB_GLOBAL_MODULE_CONFIG_NAME = os.environ['SSM_PARAMETER_DYNAMODB_GLOBAL_MODULE_CONFIG_NAME']

### Función para despliegue

In [5]:
def materiales(event, context):
    modulo: str = "modulo_mano_de_obra"
    modulo_revenue: str = "modulo_ingresos"
    PROCESS_TYPE = "er_simulado"
    modulo_global_materiales = "nombre_finca"
    file_revenue: str = "volumen.csv"
    body = event
    # # 4. Body (usually JSON, but can be other formats)
    # if event.get("body"):
    #     body = event["body"]
    #     # Assuming the body is JSON
    #     body = json.loads(body)
    #     print("body_json", body)
    #     print("type body_json", type(body))
    
    session = boto3.Session(profile_name=AWS_PROFILE)

    s3_client = session.client('s3', region_name=REGION)
    ssm_client = session.client("ssm", region_name=REGION)
    dynamodb_client = boto3.resource("dynamodb", region_name=REGION)

    bucket_input_files = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_BUCKET_INPUT_FILES_NAME,
        logger=logger,
        ssm_client=ssm_client,
        with_decryption=True,
    )
    bucket_output_files = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_BUCKET_OUTPUT_FILES_NAME,
        logger=logger,
        ssm_client=ssm_client,
        with_decryption=True,
    )
    dynamodb_table_name_module_config = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_DYNAMODB_MODULE_CONFIG_NAME,
        logger=logger,
        ssm_client=ssm_client,
        with_decryption=True,
    )

    dynamodb_table_name_global_module_config = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_DYNAMODB_GLOBAL_MODULE_CONFIG_NAME,
        logger=logger,
        ssm_client=ssm_client,
        with_decryption=True,
    )
    logger.info(f"{dynamodb_table_name_module_config}")

    module_config = get_item_from_dynamodb(
        table_name=dynamodb_table_name_module_config,
        key={"module": modulo, "process_type": PROCESS_TYPE},
        logger=logger,
        dynamodb_client=dynamodb_client,
    )

    global_config_materiales = get_item_from_dynamodb_global(
        table_name=dynamodb_table_name_global_module_config,
        partition_key_value=modulo_global_materiales,
        logger=logger,
        dynamodb_client=dynamodb_client,
   )
    
    
    input_files_names: dict = module_config["input_file_names_mano_de_obra"]
    farm_order: dict = global_config_materiales["fincas"]

    # Descarga el archivo CSV desde S3
    
    map_with_dfs = {}
    current_date = datetime.now().strftime("%Y-%m-%d")
    partition = body.get("partition", current_date)

    volum_file = object_to_dataframe(
        s3_client=s3_client,
        bucket_name=bucket_input_files,
        folder_name=f"{PROCESS_TYPE}/{modulo_revenue}",
        partition=partition,
        file_name=file_revenue,
    )

    try:
        for key, file in input_files_names.items():
            df = object_to_dataframe(
                s3_client=s3_client,
                bucket_name=bucket_input_files,
                folder_name=f"{PROCESS_TYPE}/{modulo}",
                partition=partition,
                file_name=file,
            )
            logger.info(f"file_key: {file} read successfully")
            map_with_dfs[key] = df
        volum_distribution = map_with_dfs["volum_distribution"]
    except Exception as e:
        logger.error(
            f"Error reding file {file} from {bucket_input_files}: error detail:{e}"
        )
        return Response(
            status_code=500,
            body=json.dumps(
                {
                    "message": f"Error reding file {file} from {bucket_input_files}: error detail:{e}"
                }
            ),
        )

### Importar los archivos

In [136]:
modulo: str = "modulo_mano_de_obra"
PROCESS_TYPE = "er_simulado"
dynamo_global_materiales = "nombre_finca"
modulo_global: str = "archivos_comunes_global"
output_files: str = "salida_materiales"

   
session = boto3.Session(profile_name=AWS_PROFILE)

s3_client = session.client("s3", region_name=REGION)
ssm_client = session.client("ssm", region_name=REGION)
dynamodb_client = session.resource("dynamodb", region_name=REGION)

bucket_input_files = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_BUCKET_INPUT_FILES_NAME,
        logger=logger,
        ssm_client=ssm_client,
        with_decryption=True,
    )

bucket_output_files = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_BUCKET_OUTPUT_FILES_NAME,
        logger=logger,
        ssm_client=ssm_client,
        with_decryption=True,
    )
dynamodb_table_name_module_config = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_DYNAMODB_MODULE_CONFIG_NAME,
        logger=logger,
        ssm_client=ssm_client,
        with_decryption=True,
    )

dynamodb_table_name_global_module_config = get_ssm_parameter(
        parameter_name=SSM_PARAMETER_DYNAMODB_GLOBAL_MODULE_CONFIG_NAME,
        ssm_client=ssm_client,
        logger=logger,
        with_decryption=True
    ) 
    
    
logger.info(f"{dynamodb_table_name_module_config}")

module_config = get_item_from_dynamodb(
        table_name=dynamodb_table_name_module_config,
        key={"module": modulo, "process_type": PROCESS_TYPE},
        logger=logger,
        dynamodb_client=dynamodb_client,
    )
module_config_output = get_item_from_dynamodb(
        table_name=dynamodb_table_name_module_config,
        key={"module": output_files, "process_type": PROCESS_TYPE},
        logger=logger,
        dynamodb_client=dynamodb_client,
    )

module_global_config = get_item_from_dynamodb(
        table_name=dynamodb_table_name_module_config,
        key={"module": modulo_global, "process_type": PROCESS_TYPE},
        logger=logger,
        dynamodb_client=dynamodb_client,)


global_config_materiales = get_item_from_dynamodb_global(
        table_name=dynamodb_table_name_global_module_config,
        partition_key_value=dynamo_global_materiales,
        logger=logger,
        dynamodb_client=dynamodb_client,
   )
 

input_files_names: dict = module_config["input_file_names_mo"]
input_global_file_names: dict = module_global_config["input_file_names_global"]
farm_order: dict = global_config_materiales["fincas"]
output_file_names_mat: dict = module_config_output["output_file_names_mat"]

    # Descarga el archivo CSV desde S3
map_with_dfs = {}
current_date = datetime.now().strftime("%Y-%m-%d")
partition = "2025-02-19"

#extraer los archivos del modulo global
try:
    for key, file in input_global_file_names.items():
        df = object_to_dataframe(
            s3_client=s3_client,
            bucket_name=bucket_input_files,
            folder_name=f"{PROCESS_TYPE}/{modulo_global}",
            partition=partition,
            file_name=file,
        )

        logger.info(f"file_key: {file} read successfully")
        map_with_dfs[key] = df
    volum_distribution = map_with_dfs["volum_distribution"]
    volum_file = map_with_dfs["volum_file"]
    sku = map_with_dfs["sku"]
    
except Exception as e:
    logger.error(
            f"Error reding file {file} from {bucket_input_files}: error detail:{e}"
    )
     

#extraer los archivos del modulo particular
try:
    for key, file in input_files_names.items():
        df = object_to_dataframe(
            s3_client=s3_client,
            bucket_name=bucket_input_files,
            folder_name=f"{PROCESS_TYPE}/{modulo}",
            partition=partition,
            file_name=file,
        )

        logger.info(f"file_key: {file} read successfully")
        map_with_dfs[key] = df
    cut_emp          = map_with_dfs["cut_emp"]
    promediado       = map_with_dfs["promediado"]
    revenue_sku      = map_with_dfs["revenue_sku"]
    desect_ha        = map_with_dfs["desect_ha"]
    parcela_mo       = map_with_dfs["parcela_mo"]
    esquema_mo       = map_with_dfs["esquema_mo"]
    curvas_c         = map_with_dfs["curvas_c"]
    ciclicas         = map_with_dfs["ciclicas"]
    f_labor          = map_with_dfs["f_labor"]
    other_labors     = map_with_dfs["other_labors"]
    curvas_c_mensual = map_with_dfs["curvas_c_mensual"]

except Exception as e:
    logger.error(
            f"Error reding file {file} from {bucket_input_files}: error detail:{e}"
    )

#extraer los archivos de la salida del modulo de materiales 
try:
    for key, file in output_file_names_mat.items():
        df = object_to_dataframe(
            s3_client=s3_client,
            bucket_name=bucket_output_files,
            folder_name=f"{PROCESS_TYPE}/{output_files}",
            partition=partition,
            file_name=file,
        )

        logger.info(f"file_key: {file} read successfully")
        map_with_dfs[key] = df
    salida_fertilizante   = map_with_dfs["salida_fertilizante"]
  
    
except Exception as e:
    logger.error(
            f"Error reding file {file} from {bucket_output_files}: error detail:{e}"
    )

2025-08-28 19:52:12,671 - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2025-08-28 19:52:14,077 - INFO - Parameter dev-bucket-upload-files-name retrieved successfully.
2025-08-28 19:52:14,179 - INFO - Parameter dev-tmp-bucket-name retrieved successfully.
2025-08-28 19:52:14,277 - INFO - Parameter dev-dynamodb-table-name-module-config retrieved successfully.
2025-08-28 19:52:14,378 - INFO - Parameter dev-dynamodb-table-name-global-config retrieved successfully.
2025-08-28 19:52:14,380 - INFO - dev-module-config
2025-08-28 19:52:15,307 - INFO - file_key: sku.csv read successfully
2025-08-28 19:52:15,615 - INFO - file_key: volumen.csv read successfully
2025-08-28 19:52:15,739 - INFO - file_key: distribucion_volumen.csv read successfully
2025-08-28 19:52:16,027 - INFO - file_key: labores_fijas.csv read successfully
2025-08-28 19:52:16,127 - INFO - file_key: curvas_c_mensual.csv read successfully
2025-08-28 19:52:16,239 - INFO - file_key: labores_varias.csv read successfully
2025-08-28 19:52:16,391 - INFO - file_key: curvas_g.csv read successfully
2025-08-28 19:52:16,574 - INFO - file_key: corte_y_empaque.csv read successfully
2025-08-28 19:52:16,673 - INFO - file_key: desect_ha_mo.csv read successfully
2025-08-28 19:52:16,807 - INFO - file_key: esquemas.csv read successfully
2025-08-28 19:52:17,057 - INFO - file_key: input_mo.csv read successfully
2025-08-28 19:52:17,274 - INFO - file_key: ciclicas.csv read successfully
2025-08-28 19:52:17,395 - INFO - file_key: curvas_c.csv read successfully
2025-08-28 19:52:17,517 - INFO - file_key: parcela.csv read successfully
2025-08-28 19:52:17,855 - INFO - file_key: salida_fertilizante.csv read successfully

## Corte y empaque

### labor 100001

In [7]:
volum_file.columns = list(volum_file.columns[:3]) + [pd.to_datetime(col, dayfirst=True, errors='coerce') for col in volum_file.columns[3:]]

In [8]:
volum_distribution.columns = list(volum_distribution.columns[:1]) + [pd.to_datetime(col, dayfirst=True, errors='coerce') for col in volum_distribution.columns[1:]]

In [9]:
volum_file_subset = volum_file.iloc[:,3:]

In [10]:
group_data = group_by_month(volum_file_subset, volum_file)
month_columns = group_data.iloc[:, 2:].columns

2025-08-28 19:41:23,324 - INFO - Inicia la función agrupando por mes.
2025-08-28 19:41:23,326 - INFO - agrupando las columnas por mes y sumandolas.
2025-08-28 19:41:23,330 - INFO - Se realizó la agrupación con éxito.

In [11]:
volum_distribution_matrix = volum_distribution.iloc[:, 1:]
volum_file_matrix = volum_file[volum_file['CONCEPTO'] == 'CAJAS'].iloc[:, 3:]
volum_file_subset = volum_file[volum_file['CONCEPTO'] == 'CAJAS']

In [12]:
full_matrix = volum_file_subset.merge(cut_emp, on=['FINCA'], how='inner')
full_matrix_100001 = full_matrix[full_matrix['ID'] == 100001]
factor_100001 = full_matrix_100001.FACTOR.reset_index(drop=True)

In [13]:
quantity_100001 = calculate_volume_distribution_factor(volum_file_matrix, volum_distribution_matrix, volum_file_subset, month_columns, factor_100001)

2025-08-28 19:41:23,403 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-08-28 19:41:23,534 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [14]:
labor_100001 = multiply_price(quantity_100001, full_matrix_100001, 'FINCA', 'TARIFA', 'PROMEDIADO', month_columns)

2025-08-28 19:41:23,557 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:23,557 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:23,568 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:23,568 - INFO - Proceso completado exitosamente.

In [15]:
promediado_100001 = multiply_by_month_promediado(labor_100001, promediado, month_columns)

2025-08-28 19:41:23,595 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:23,601 - INFO - Proceso completado exitosamente

In [16]:
social_p_100001 = multiply_p_social(labor_100001, promediado_100001,full_matrix_100001, 'FINCA', 'PRESTACIONES', 'LABOR',month_columns)

2025-08-28 19:41:23,621 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:23,627 - INFO - Suma realizada con éxito.
2025-08-28 19:41:23,633 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:23,634 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:23,634 - INFO - Proceso completado exitosamente.

In [17]:
cost_100001 = total_cost(labor_100001, promediado_100001, social_p_100001, 'FINCA', 'LABOR', month_columns)

2025-08-28 19:41:23,659 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:23,673 - INFO - Suma realizada con éxito.
2025-08-28 19:41:23,673 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:23,678 - INFO - Proceso completado exitosamente.

### labor 100002 -5

In [18]:

volum_distribution_matrix = volum_distribution.iloc[:, 1:]

volum_file_matrix_10002 = volum_file[volum_file['CONCEPTO'] == 'CORTADOS'].iloc[:, 3:]
volum_file_subset_10002 = volum_file[volum_file['CONCEPTO'] == 'CORTADOS']

full_matrix_100002 = volum_file_subset_10002.merge(cut_emp, on=['FINCA'], how='inner')
full_matrix_100002 = full_matrix[full_matrix['ID'] == 100002]
full_matrix_100003 = full_matrix[full_matrix['ID'] == 100003]
full_matrix_100004 = full_matrix[full_matrix['ID'] == 100004]
full_matrix_100005 = full_matrix[full_matrix['ID'] == 100005]

factor_100002 = full_matrix_100002.FACTOR.reset_index(drop=True)
factor_100003 = full_matrix_100003.FACTOR.reset_index(drop=True)
factor_100004 = full_matrix_100004.FACTOR.reset_index(drop=True)
factor_100005 = full_matrix_100005.FACTOR.reset_index(drop=True)

In [19]:
quantity_100002 = calculate_volume_distribution_factor(volum_file_matrix_10002, volum_distribution_matrix, volum_file_subset_10002, month_columns, factor_100002)

2025-08-28 19:41:23,727 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-08-28 19:41:23,851 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [20]:
quantity_100003 = calculate_volume_distribution_factor(volum_file_matrix_10002, 
                                                       volum_distribution_matrix, 
                                                       volum_file_subset_10002, month_columns, 
                                                       factor_100003)

2025-08-28 19:41:23,877 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.

2025-08-28 19:41:23,991 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [21]:
quantity_100004 = calculate_volume_distribution_factor(volum_file_matrix_10002, 
                                                       volum_distribution_matrix, 
                                                       volum_file_subset_10002, month_columns, 
                                                       factor_100004)

2025-08-28 19:41:24,010 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.

2025-08-28 19:41:24,118 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [22]:
quantity_100005 = calculate_volume_distribution_factor(volum_file_matrix_10002, 
                                                       volum_distribution_matrix, 
                                                       volum_file_subset_10002, month_columns, 
                                                       factor_100005)

2025-08-28 19:41:24,134 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-08-28 19:41:24,238 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [23]:
labor_100002 = multiply_price(quantity_100002, full_matrix_100002, 'FINCA', 'TARIFA', 'PROMEDIADO', month_columns)
labor_100003 = multiply_price(quantity_100003, full_matrix_100003, 'FINCA', 'TARIFA', 'PROMEDIADO', month_columns)
labor_100004 = multiply_price(quantity_100004, full_matrix_100004, 'FINCA', 'TARIFA', 'PROMEDIADO', month_columns)
labor_100005 = multiply_price(quantity_100005, full_matrix_100005, 'FINCA', 'TARIFA', 'PROMEDIADO', month_columns)

2025-08-28 19:41:24,248 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:24,248 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:24,264 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:24,268 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:24,268 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:24,268 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:24,276 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:24,276 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:24,276 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:24,279 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:24,284 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:24,284 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:24,284 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:24,284 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:24,293 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:24,293 - INFO - Proceso completado exitosamente.

In [24]:
promediado_100002 = multiply_by_month_promediado(labor_100002, promediado, month_columns)
promediado_100003 = multiply_by_month_promediado(labor_100003, promediado, month_columns)
promediado_100004 = multiply_by_month_promediado(labor_100004, promediado, month_columns)
promediado_100005 = multiply_by_month_promediado(labor_100005, promediado, month_columns)

2025-08-28 19:41:24,314 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:24,317 - INFO - Proceso completado exitosamente
2025-08-28 19:41:24,317 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:24,341 - INFO - Proceso completado exitosamente
2025-08-28 19:41:24,348 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:24,350 - INFO - Proceso completado exitosamente
2025-08-28 19:41:24,361 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:24,367 - INFO - Proceso completado exitosamente

In [25]:
social_p_100002 = multiply_p_social(labor_100002, 
                                    promediado_100002,full_matrix_100002, 
                                    'FINCA', 'PRESTACIONES', 
                                    'LABOR',month_columns)

social_p_100003 = multiply_p_social(labor_100003, 
                                    promediado_100003,full_matrix_100003, 
                                    'FINCA', 'PRESTACIONES', 
                                    'LABOR',month_columns)
social_p_100004 = multiply_p_social(labor_100004, 
                                    promediado_100004,full_matrix_100004, 
                                    'FINCA', 'PRESTACIONES', 
                                    'LABOR',month_columns)
social_p_100005 = multiply_p_social(labor_100005, 
                                    promediado_100005,full_matrix_100005, 
                                    'FINCA', 'PRESTACIONES', 
                                    'LABOR',month_columns)

2025-08-28 19:41:24,382 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:24,398 - INFO - Suma realizada con éxito.
2025-08-28 19:41:24,398 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:24,398 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:24,398 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:24,398 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:24,414 - INFO - Suma realizada con éxito.
2025-08-28 19:41:24,417 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:24,418 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:24,418 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:24,418 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:24,418 - INFO - Suma realizada con éxito.
2025-08-28 19:41:24,418 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:24,434 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:24,434 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:24,434 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:24,434 - INFO - Suma realizada con éxito.
2025-08-28 19:41:24,434 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:24,449 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:24,449 - INFO - Proceso completado exitosamente.

In [26]:
cost_100002 = total_cost(labor_100002, promediado_100002, social_p_100002, 'FINCA', 'LABOR', month_columns)
cost_100003 = total_cost(labor_100003, promediado_100003, social_p_100003, 'FINCA', 'LABOR', month_columns)
cost_100004 = total_cost(labor_100004, promediado_100004, social_p_100004, 'FINCA', 'LABOR', month_columns)
cost_100005 = total_cost(labor_100005, promediado_100005, social_p_100005, 'FINCA', 'LABOR', month_columns)

2025-08-28 19:41:24,474 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:24,483 - INFO - Suma realizada con éxito.
2025-08-28 19:41:24,485 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:24,488 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:24,490 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:24,496 - INFO - Suma realizada con éxito.
2025-08-28 19:41:24,497 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:24,502 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:24,502 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:24,502 - INFO - Suma realizada con éxito.
2025-08-28 19:41:24,502 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:24,502 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:24,502 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:24,521 - INFO - Suma realizada con éxito.
2025-08-28 19:41:24,521 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:24,525 - INFO - Proceso completado exitosamente.

### labor promediados

In [27]:
full_matrix_promediados_100006 = full_matrix[full_matrix['ID'] == 100006]
full_matrix_promediados_1000023 = full_matrix[full_matrix['ID'] == 100023]
factor_promediados_100006 = full_matrix_promediados_100006.FACTOR.reset_index(drop=True)
factor_promediados_1000023 = full_matrix_promediados_1000023.FACTOR.reset_index(drop=True)
factor_concat = pd.concat([factor_promediados_100006, factor_promediados_1000023], ignore_index=True)

In [28]:
quantity_promediados = calculate_promediados_factor(volum_distribution_matrix, volum_file_subset, month_columns, factor_concat)

2025-08-28 19:41:24,554 - INFO - Iniciando el cálculo de la matriz de distribución de volumen con 92 factores.
2025-08-28 19:41:24,554 - INFO - Procesando el mes: 0
2025-08-28 19:41:24,573 - INFO - Procesando el mes: 1
2025-08-28 19:41:24,584 - INFO - Procesando el mes: 2
2025-08-28 19:41:24,600 - INFO - Procesando el mes: 3
2025-08-28 19:41:24,600 - INFO - Procesando el mes: 4
2025-08-28 19:41:24,616 - INFO - Procesando el mes: 5
2025-08-28 19:41:24,641 - INFO - Procesando el mes: 6
2025-08-28 19:41:24,650 - INFO - Procesando el mes: 7
2025-08-28 19:41:24,666 - INFO - Procesando el mes: 8
2025-08-28 19:41:24,682 - INFO - Procesando el mes: 9
2025-08-28 19:41:24,682 - INFO - Procesando el mes: 10
2025-08-28 19:41:24,700 - INFO - Procesando el mes: 11
2025-08-28 19:41:24,716 - INFO - Matriz de resultados generada.
2025-08-28 19:41:24,716 - INFO - Matriz de resultados transpuesta y columnas renombradas.
2025-08-28 19:41:24,716 - INFO - DataFrame final concatenado con los datos de volumen transformados.

In [29]:
quantity_promediados_100023 = quantity_promediados.iloc[46:, :]
quantity_promediados_100006 = quantity_promediados.iloc[0:46, :]

In [30]:
labor_promediados_100023 = multiply_price(quantity_promediados_100023, 
                                          full_matrix_promediados_1000023, 
                                          'FINCA', 'TARIFA', 'PROMEDIADO', 
                                          month_columns)

2025-08-28 19:41:24,755 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:24,757 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:24,767 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:24,769 - INFO - Proceso completado exitosamente.

In [31]:
labor_promediados_100006 = multiply_price(quantity_promediados_100006, 
                                          full_matrix_promediados_100006, 
                                          'FINCA', 'TARIFA', 'PROMEDIADO', 
                                          month_columns)

2025-08-28 19:41:24,787 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:24,790 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:24,795 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:24,798 - INFO - Proceso completado exitosamente.

In [32]:
promediado_100023 = multiply_by_month_promediado(labor_promediados_100023, promediado, month_columns)
promediado_100006 = multiply_by_month_promediado(labor_promediados_100006, promediado, month_columns)

2025-08-28 19:41:24,825 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:24,838 - INFO - Proceso completado exitosamente
2025-08-28 19:41:24,843 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:24,851 - INFO - Proceso completado exitosamente

In [33]:
social_promediado_100023 = multiply_p_social(labor_promediados_100023, 
                                    promediado_100023 ,full_matrix_promediados_1000023, 
                                    'FINCA', 'PRESTACIONES', 
                                    'LABOR',month_columns)

social_promediado_1000006 = multiply_p_social(labor_promediados_100006,
                                    promediado_100006 ,full_matrix_promediados_100006, 
                                    'FINCA', 'PRESTACIONES', 
                                    'LABOR',month_columns)

2025-08-28 19:41:24,877 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:24,884 - INFO - Suma realizada con éxito.
2025-08-28 19:41:24,884 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:24,884 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:24,884 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:24,884 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:24,901 - INFO - Suma realizada con éxito.
2025-08-28 19:41:24,902 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:24,907 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:24,907 - INFO - Proceso completado exitosamente.

In [34]:
cost_promediado_100023 = total_cost(labor_promediados_100023, promediado_100023, social_promediado_100023, 'FINCA', 'LABOR', month_columns)
cost_promediado_100006 = total_cost(labor_promediados_100006, promediado_100006, social_promediado_1000006, 'FINCA', 'LABOR', month_columns)

2025-08-28 19:41:24,917 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:24,934 - INFO - Suma realizada con éxito.
2025-08-28 19:41:24,934 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:24,936 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:24,936 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:24,936 - INFO - Suma realizada con éxito.
2025-08-28 19:41:24,936 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:24,949 - INFO - Proceso completado exitosamente.

### cantidades modulo ingreso

In [35]:
revenue_sku_subset = revenue_sku[revenue_sku['SKU']!= 'Exc-']
revenue_sku_subset.loc[:, 'Farm'] = revenue_sku_subset['Farm'].astype(str).apply(unidecode)

In [36]:
input_mo_join = pd.merge(revenue_sku_subset, sku[['SKU', 'TIPO']] ,how = 'left', on = 'SKU')
input_mo_join.rename(columns={'Farm':'FINCA'}, inplace=True)

In [37]:
mo_grouped_total = group_by_type(input_mo_join, farms=farm_order)

2025-08-28 19:41:25,041 - INFO - Iniciando limpieza de columnas TIPO y FINCA...
2025-08-28 19:41:25,041 - INFO - Renombrando columnas de fechas al tipo Timestamp (posición 3 a penúltima)...
2025-08-28 19:41:25,045 - INFO - Obteniendo valores únicos de TIPO...
2025-08-28 19:41:25,045 - INFO - Creando combinaciones TIPO-FINCA completas...
2025-08-28 19:41:25,045 - INFO - Agrupando por TIPO y FINCA...
2025-08-28 19:41:25,059 - INFO - Uniendo con combinaciones completas...
2025-08-28 19:41:25,061 - INFO - Rellenando NaNs con ceros...
2025-08-28 19:41:25,061 - INFO - Proceso de agrupación finalizado exitosamente.

In [38]:
mo_pre_100008 = merge_factor_by_id(100008, mo_grouped_total, cut_emp)
mo_pre_100008_final = multipy_factor_combined(mo_pre_100008, 'PRE')
mo_pre_100008_final_subset = mo_pre_100008_final.iloc[:,2:54]
full_matrix_100008 = full_matrix[full_matrix['ID'] == 100008]
factor_100008 = full_matrix_100008.FACTOR.reset_index(drop=True)

2025-08-28 19:41:25,102 - INFO - Filtrando por TIPO = PRE
2025-08-28 19:41:25,103 - INFO - Aplicando FACTOR a columnas numéricas...

In [39]:
mo_100009 = group_by_type_sum(input_mo_join, farms=farm_order, types_sum=['EDK', 'ESP'])
mo_100009_factor = merge_factor_by_id(100009, mo_100009, cut_emp)
mo_100009_final =  multipy_factor_combined(mo_100009_factor, 'EDK+ESP')
mo_100009_final_subset = mo_100009_final.iloc[:,2:54]

2025-08-28 19:41:25,127 - INFO - Iniciando limpieza de columnas TIPO y FINCA...
2025-08-28 19:41:25,127 - INFO - Obteniendo valores únicos de TIPO...
2025-08-28 19:41:25,127 - INFO - Creando combinaciones TIPO-FINCA completas...
2025-08-28 19:41:25,127 - INFO - Agrupando por TIPO y FINCA...
2025-08-28 19:41:25,136 - INFO - Uniendo con combinaciones completas...
2025-08-28 19:41:25,136 - INFO - Rellenando NaNs con ceros...
2025-08-28 19:41:25,141 - INFO - Sumando tipos especificados: ['EDK', 'ESP']
2025-08-28 19:41:25,141 - INFO - Agregando fila de suma de tipos al DataFrame final...
2025-08-28 19:41:25,141 - INFO - Proceso de agrupación y orden finalizado exitosamente.
2025-08-28 19:41:25,151 - INFO - Filtrando por TIPO = EDK+ESP
2025-08-28 19:41:25,151 - INFO - Aplicando FACTOR a columnas numéricas...

In [40]:
mo_100010 = group_by_type_sum(input_mo_join, farms=farm_order, types_sum=['ESP', 'MG'])
mo_100010_factor = merge_factor_by_id(100010, mo_100010, cut_emp)
mo_100010_final = multipy_factor_combined(mo_100010_factor, 'ESP+MG')
mo_100010_final_subset = mo_100010_final.iloc[:,2:54]

2025-08-28 19:41:25,167 - INFO - Iniciando limpieza de columnas TIPO y FINCA...
2025-08-28 19:41:25,179 - INFO - Obteniendo valores únicos de TIPO...
2025-08-28 19:41:25,179 - INFO - Creando combinaciones TIPO-FINCA completas...
2025-08-28 19:41:25,179 - INFO - Agrupando por TIPO y FINCA...
2025-08-28 19:41:25,187 - INFO - Uniendo con combinaciones completas...
2025-08-28 19:41:25,187 - INFO - Rellenando NaNs con ceros...
2025-08-28 19:41:25,187 - INFO - Sumando tipos especificados: ['ESP', 'MG']
2025-08-28 19:41:25,196 - INFO - Agregando fila de suma de tipos al DataFrame final...
2025-08-28 19:41:25,196 - INFO - Proceso de agrupación y orden finalizado exitosamente.
2025-08-28 19:41:25,201 - INFO - Filtrando por TIPO = ESP+MG
2025-08-28 19:41:25,201 - INFO - Aplicando FACTOR a columnas numéricas...

In [41]:
mo_100011_factor = merge_factor_by_id(100011, mo_grouped_total, cut_emp)
mo_100011_final = multipy_factor_combined(mo_100011_factor, 'PRE')
mo_100011_final_subset = mo_100011_final.iloc[:,2:54]

2025-08-28 19:41:25,227 - INFO - Filtrando por TIPO = PRE
2025-08-28 19:41:25,232 - INFO - Aplicando FACTOR a columnas numéricas...

In [42]:
mo_100012_factor = merge_factor_by_id(100012, mo_grouped_total, cut_emp)
mo_100012_final = multipy_factor_combined(mo_100012_factor, 'WT')
mo_100012_final_subset = mo_100012_final.iloc[:,2:54]

2025-08-28 19:41:25,262 - INFO - Filtrando por TIPO = WT
2025-08-28 19:41:25,262 - INFO - Aplicando FACTOR a columnas numéricas...

In [43]:
mo_100013_factor = merge_factor_by_id(100013, mo_grouped_total, cut_emp)
mo_100013_final = multipy_factor_combined(mo_100013_factor, 'MG')
mo_100013_final_subset = mo_100013_final.iloc[:,2:54]

2025-08-28 19:41:25,288 - INFO - Filtrando por TIPO = MG
2025-08-28 19:41:25,298 - INFO - Aplicando FACTOR a columnas numéricas...

In [44]:
mo_08_13_concat = pd.concat([mo_pre_100008_final, mo_100009_final, mo_100010_final, 
                                   mo_100011_final, mo_100012_final, mo_100013_final], axis = 0)
mo_08_13_concat_subset = mo_08_13_concat.iloc[:,2:54]

In [45]:
quantity_08_13 = calculate_volume_distribution_blocks(mo_08_13_concat_subset, volum_distribution_matrix, volum_file_subset, month_columns)

2025-08-28 19:41:25,333 - INFO - Iniciando cálculo de volumen por bloques de 46 filas.
2025-08-28 19:41:25,921 - INFO - Cálculo de matriz de volumen completado correctamente.

In [46]:
id_list = [100008,100009, 100010, 100011, 100012, 100013]
full_matrix_block = full_matrix[full_matrix['ID'].isin(id_list)]
full_matrix_block.loc[:, 'FINCA'] = full_matrix_block['FINCA'].astype(str).apply(unidecode) 
full_matrix_block_subset = full_matrix_block[['ID', 'FINCA', 'PROMEDIADO', 'TARIFA']]

In [47]:
# Convertimos la columna 'FINCA' a categoría con el orden deseado
full_matrix_block_subset['FINCA'] = pd.Categorical(
    full_matrix_block_subset['FINCA'],
    categories=farm_order,
    ordered=True
)

# Ordenamos por ID descendente y luego por FINCA según farm_order
full_matrix_block_subset_sorted = full_matrix_block_subset.sort_values(
    by=['ID', 'FINCA'],
    ascending=[True, True]  # ID descendente, FINCA según orden de categorías
)

In [48]:
labor_08_13_concat = pd.concat([quantity_08_13.reset_index(drop=True), 
                                   full_matrix_block_subset_sorted.reset_index(drop=True)], 
                                   axis = 1)

In [49]:
# Paso 1: Guardar una vez los valores originales de los meses
if f'original_{month_columns[0]}' not in labor_08_13_concat.columns:
    for col in month_columns:
        labor_08_13_concat[f'original_{col}'] = labor_08_13_concat[col]

# Paso 2: Multiplicar siempre desde los originales
for col in month_columns:
    labor_08_13_concat[col] = labor_08_13_concat[f'original_{col}'] * labor_08_13_concat['TARIFA']

In [50]:
labor_08_13_subset = labor_08_13_concat[['FINCA', 'PROMEDIADO'] + list(month_columns)]
labor_08_13_subset.columns = labor_08_13_subset.columns.astype(str).str.strip()

In [51]:
promediado_08_13 = multiply_by_month_promediado(labor_08_13_subset, promediado, month_columns)

2025-08-28 19:41:26,040 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:26,056 - INFO - Proceso completado exitosamente

In [52]:
# Convertimos la columna 'FINCA' a categoría con el orden deseado
full_matrix_block['FINCA'] = pd.Categorical(
    full_matrix_block['FINCA'],
    categories=farm_order,
    ordered=True
)

# Ordenamos por ID descendente y luego por FINCA según farm_order
full_matrix_block_sorted = full_matrix_block.sort_values(
    by=['ID', 'FINCA'],
    ascending=[True, True]  # ID descendente, FINCA según orden de categorías
).reset_index(drop = True)

In [53]:
full_matrix_block_sorted_social = full_matrix_block_sorted[['FINCA', 'PRESTACIONES', 'LABOR', 'ID']]
labor_08_13_social = pd.concat([labor_08_13_subset, full_matrix_block_sorted_social], axis = 1)

In [54]:
social_p_08_13 = multiply_p_social_block(labor_08_13_social, promediado_08_13,full_matrix_block_sorted_social,month_columns)

2025-08-28 19:41:26,128 - INFO - Inicia la función de suma y multiplicación con PRESTACIONES.
2025-08-28 19:41:26,135 - INFO - Suma realizada con éxito.
2025-08-28 19:41:26,135 - INFO - Multiplicación con PRESTACIONES completada.

In [55]:
labor_08_13_social_cost = labor_08_13_social.iloc[:, 1:]
cost_08_13 = total_cost_block(labor_08_13_social_cost, promediado_08_13, social_p_08_13, 'FINCA', 'LABOR', month_columns)

2025-08-28 19:41:26,155 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:26,169 - INFO - Suma realizada con éxito.
2025-08-28 19:41:26,169 - INFO - Realizando el merge sobre la columna FINCA y LABOR
2025-08-28 19:41:26,169 - INFO - Proceso completado exitosamente.

In [56]:
id_list_2 = [100014,100015, 100016, 100017, 100018, 100019]
full_matrix_14_19_id = full_matrix[full_matrix['ID'].isin(id_list_2)]

In [57]:
#este codigo se utiliza para hacer un bucle for sobre todos los id que se encuentran en la lista id_list_2 y su formula corresponde con 
#la función calculate_volume_distribution_factor idem para el resto de calculos de labores, promediados, y costo total
quantity_list = []

for id_value in id_list_2:
    factor_series = full_matrix_14_19_id[full_matrix_14_19_id['ID'] == id_value]['FACTOR'].reset_index(drop=True)

    quantity_df = calculate_volume_distribution_factor(
        volum_file_matrix,
        volum_distribution_matrix,
        volum_file_subset,
        month_columns,
        factor_series
    )

    quantity_df['ID'] = id_value  # Añades el ID para identificar luego
    quantity_list.append(quantity_df)

# Unir todos los quantity en un solo DataFrame
quantity_all_df = pd.concat(quantity_list, ignore_index=True)

2025-08-28 19:41:26,205 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-08-28 19:41:26,301 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.
2025-08-28 19:41:26,301 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-08-28 19:41:26,450 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.
2025-08-28 19:41:26,452 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-08-28 19:41:26,551 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.
2025-08-28 19:41:26,551 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-08-28 19:41:26,668 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.
2025-08-28 19:41:26,668 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-08-28 19:41:26,768 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.
2025-08-28 19:41:26,768 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-08-28 19:41:26,867 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [58]:
labor_list = []

for id_value in id_list_2:
    # Filtrar los datos que corresponden a ese ID
    quantity_df = quantity_all_df[quantity_all_df['ID'] == id_value].reset_index(drop=True)
    filtered_df = full_matrix_14_19_id[full_matrix_14_19_id['ID'] == id_value].reset_index(drop=True)

    labor_df = multiply_price(
        quantity_df,
        filtered_df,
        'FINCA',
        'TARIFA',
        'PROMEDIADO',
        month_columns
    )

    labor_df['ID'] = id_value
    labor_list.append(labor_df)

# Unir todos los resultados en un solo DataFrame
final_labor_df_14_19 = pd.concat(labor_list, ignore_index=True)

2025-08-28 19:41:26,884 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:26,884 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:26,901 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'ID', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:26,901 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:26,901 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:26,901 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:26,901 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'ID', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:26,917 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:26,918 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:26,918 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:26,918 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'ID', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:26,918 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:26,918 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:26,918 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:26,934 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'ID', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:26,934 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:26,934 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:26,934 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:26,934 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'ID', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:26,949 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:26,951 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:26,951 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:26,951 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'ID', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:26,960 - INFO - Proceso completado exitosamente.

In [59]:
promediado_results = []

for id_value in id_list_2:
    labor_df = final_labor_df_14_19[final_labor_df_14_19['ID'] == id_value].reset_index(drop=True)

    promediado_df = multiply_by_month_promediado(
        labor_df,
        promediado,
        month_columns
    )
    
    promediado_df['ID'] = id_value
    promediado_results.append(promediado_df)

# Concatenar en un solo DataFrame final
final_promediado_df_14_19 = pd.concat(promediado_results, ignore_index=True)

2025-08-28 19:41:26,986 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'ID', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:26,993 - INFO - Proceso completado exitosamente
2025-08-28 19:41:27,009 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'ID', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:27,019 - INFO - Proceso completado exitosamente
2025-08-28 19:41:27,026 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'ID', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:27,040 - INFO - Proceso completado exitosamente
2025-08-28 19:41:27,048 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'ID', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:27,058 - INFO - Proceso completado exitosamente
2025-08-28 19:41:27,067 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'ID', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:27,076 - INFO - Proceso completado exitosamente
2025-08-28 19:41:27,076 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'ID', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:27,088 - INFO - Proceso completado exitosamente

In [60]:
social_p_results = []

for id_value in id_list_2:
    labor_df = final_labor_df_14_19[final_labor_df_14_19['ID'] == id_value].reset_index(drop=True)
    promediado_df = final_promediado_df_14_19[final_promediado_df_14_19['ID'] == id_value].reset_index(drop=True)
    filtered_matrix = full_matrix_14_19_id[full_matrix_14_19_id['ID'] == id_value].reset_index(drop=True)

    social_df = multiply_p_social(
        labor_df,
        promediado_df,
        filtered_matrix,
        'FINCA',
        'PRESTACIONES',
        'LABOR',
        month_columns
    )
    
    social_df['ID'] = id_value
    social_p_results.append(social_df)

# Concatenar resultados en un solo DataFrame final
final_social_p_df_14_19 = pd.concat(social_p_results, ignore_index=True)

2025-08-28 19:41:27,101 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:27,120 - INFO - Suma realizada con éxito.
2025-08-28 19:41:27,120 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:27,120 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:27,120 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:27,120 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:27,134 - INFO - Suma realizada con éxito.
2025-08-28 19:41:27,134 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:27,134 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:27,134 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:27,149 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:27,149 - INFO - Suma realizada con éxito.
2025-08-28 19:41:27,149 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:27,149 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:27,149 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:27,165 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:27,165 - INFO - Suma realizada con éxito.
2025-08-28 19:41:27,165 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:27,165 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:27,181 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:27,184 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:27,184 - INFO - Suma realizada con éxito.
2025-08-28 19:41:27,184 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:27,197 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:27,197 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:27,200 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:27,200 - INFO - Suma realizada con éxito.
2025-08-28 19:41:27,200 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:27,213 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:27,213 - INFO - Proceso completado exitosamente.

In [61]:
cost_results = []

for id_value in id_list_2:
    labor_df = final_labor_df_14_19[final_labor_df_14_19['ID'] == id_value].reset_index(drop=True)
    promediado_df = final_promediado_df_14_19[final_promediado_df_14_19['ID'] == id_value].reset_index(drop=True)
    social_p_df = final_social_p_df_14_19[final_social_p_df_14_19['ID'] == id_value].reset_index(drop=True)

    cost_df = total_cost(
        labor_df,
        promediado_df,
        social_p_df,
        'FINCA',
        'LABOR',
        month_columns
    )
    
    cost_df['ID'] = id_value
    cost_results.append(cost_df)

# Concatenar resultados en un solo DataFrame final
final_cost_df_14_19 = pd.concat(cost_results, ignore_index=True)

2025-08-28 19:41:27,241 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:27,249 - INFO - Suma realizada con éxito.
2025-08-28 19:41:27,249 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:27,249 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:27,249 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:27,261 - INFO - Suma realizada con éxito.
2025-08-28 19:41:27,268 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:27,268 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:27,268 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:27,284 - INFO - Suma realizada con éxito.
2025-08-28 19:41:27,285 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:27,289 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:27,291 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:27,300 - INFO - Suma realizada con éxito.
2025-08-28 19:41:27,300 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:27,300 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:27,300 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:27,316 - INFO - Suma realizada con éxito.
2025-08-28 19:41:27,316 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:27,316 - INFO - Proceso completado exitosamente.
2025-08-28 19:41:27,325 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:27,331 - INFO - Suma realizada con éxito.
2025-08-28 19:41:27,333 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:27,337 - INFO - Proceso completado exitosamente.

In [62]:
volum_file_matrix_binaria = (volum_file_matrix > 0).astype(int)

In [63]:
full_matrix_100020 = full_matrix[full_matrix['ID'] == 100020]
factor_100020 = full_matrix_100020.FACTOR.reset_index(drop=True)

In [64]:
quantity_df_100020 = calculate_volume_distribution_factor(
        volum_file_matrix_binaria,
        volum_distribution_matrix,
        volum_file_subset,
        month_columns,
        factor_100020
    )

2025-08-28 19:41:27,392 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-08-28 19:41:27,481 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [65]:
labor_100020 = multiply_price(quantity_df_100020, 
                              full_matrix_100020, 
                              'FINCA', 'TARIFA', 'PROMEDIADO', 
                              month_columns)

2025-08-28 19:41:27,510 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:27,511 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:27,518 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:27,518 - INFO - Proceso completado exitosamente.

In [66]:
promediado_100020 = multiply_by_month_promediado(labor_100020, 
                                                 promediado, 
                                                 month_columns)

2025-08-28 19:41:27,541 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:27,557 - INFO - Proceso completado exitosamente

In [67]:
social_p_100020 = multiply_p_social(labor_100020, 
                                    promediado_100020,
                                    full_matrix_100020,
                                    'FINCA', 'PRESTACIONES', 'LABOR',
                                    month_columns)

2025-08-28 19:41:27,569 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:27,584 - INFO - Suma realizada con éxito.
2025-08-28 19:41:27,585 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:27,585 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:27,585 - INFO - Proceso completado exitosamente.

In [68]:
cost_100020 = total_cost(labor_100020, 
                          promediado_100020, 
                          social_p_100020, 
                          'FINCA', 'LABOR', 
                          month_columns)

2025-08-28 19:41:27,608 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:27,620 - INFO - Suma realizada con éxito.
2025-08-28 19:41:27,620 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:27,620 - INFO - Proceso completado exitosamente.

In [69]:
mo_100009_final =  multipy_factor_combined(mo_100009_factor, 'EDK+ESP')

2025-08-28 19:41:27,637 - INFO - Filtrando por TIPO = EDK+ESP
2025-08-28 19:41:27,637 - INFO - Aplicando FACTOR a columnas numéricas...

In [70]:
mo_100021_factor = merge_factor_by_id(100021, mo_grouped_total, cut_emp)
mo_100021_mg = multipy_factor_combined_100021(mo_100021_factor, 'MG', 3)
mo_100021_edk = multipy_factor_combined_100021(mo_100021_factor, 'EDK',2)
mo_100021_mg_subset = mo_100021_mg.iloc[:,2:54].reset_index(drop=True)
mo_100021_edk_subset = mo_100021_edk.iloc[:,2:54].reset_index(drop=True)

2025-08-28 19:41:27,733 - INFO - Filtrando por TIPO = MG
2025-08-28 19:41:27,733 - INFO - Aplicando FACTOR a columnas numéricas...
2025-08-28 19:41:27,753 - INFO - Filtrando por TIPO = EDK
2025-08-28 19:41:27,753 - INFO - Aplicando FACTOR a columnas numéricas...

In [71]:
factor_100021 = full_matrix[full_matrix['ID'] == 100021].reset_index(drop = True).FACTOR
full_matrix_100021 = full_matrix[full_matrix['ID'] == 100021].reset_index(drop = True)
mg_plus_edk = pd.DataFrame()

for date in mo_100021_edk_subset.columns:
    mg_plus_edk[date] = mo_100021_mg_subset[date] + mo_100021_edk_subset[date]

In [72]:
quantity_mg_edk = calculate_volume_distribution_factor(
        mg_plus_edk,
        volum_distribution_matrix,
        volum_file_subset,
        month_columns,
        factor_100021
    )

2025-08-28 19:41:27,826 - INFO - Iniciando el cálculo de la matriz de distribución de volumen.
2025-08-28 19:41:28,009 - INFO - Factores de ajuste aplicados al DataFrame transpuesto.

In [73]:
labor_100021 = multiply_price(
        quantity_mg_edk,
        full_matrix_100021,
        'FINCA',
        'TARIFA',
        'PROMEDIADO',
        month_columns
    )

2025-08-28 19:41:28,020 - INFO - Inicia la función para multiplicar los DataFrames.
2025-08-28 19:41:28,029 - INFO - Realizando el merge sobre la columna FINCA
2025-08-28 19:41:28,037 - INFO - Columnas posteriores a la multiplicación: ['FINCA', 'CONCEPTO', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'TARIFA', 'PROMEDIADO']
2025-08-28 19:41:28,037 - INFO - Proceso completado exitosamente.

In [74]:

promediado_100021 = multiply_by_month_promediado(labor_100021,
                                          promediado, 
                                          month_columns
                                          )

2025-08-28 19:41:28,068 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:28,077 - INFO - Proceso completado exitosamente

In [75]:
social_100021 = multiply_p_social(labor_100021,
                                  promediado_100021,
                                  full_matrix_100021,
                                  'FINCA',
                                  'PRESTACIONES',
                                  'LABOR',
                                   month_columns)

2025-08-28 19:41:28,094 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:28,102 - INFO - Suma realizada con éxito.
2025-08-28 19:41:28,102 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:28,102 - INFO - Columnas posteriores a la multiplicación: ['FINCA', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', 'PRESTACIONES', 'LABOR']
2025-08-28 19:41:28,102 - INFO - Proceso completado exitosamente.

In [76]:
cost_100021 = total_cost(
        labor_100021,
        promediado_100021,
        social_100021,
        'FINCA',
        'LABOR',
        month_columns
    )

2025-08-28 19:41:28,128 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:28,140 - INFO - Suma realizada con éxito.
2025-08-28 19:41:28,141 - INFO - Realizando el merge sobre la columna FINCA y PRESTACIONES
2025-08-28 19:41:28,148 - INFO - Proceso completado exitosamente.

### CONCATENAMOS TODOS LOS ID POR LABOR, PROMEDIADO, P SOCIALES Y COSTO

In [77]:
#labor 

total_labor_concat = pd.concat([labor_100001, labor_100002, labor_100003, labor_100004,
                                labor_100005, labor_promediados_100006, labor_promediados_100023, 
                                labor_08_13_concat, final_labor_df_14_19, labor_100020,
                                labor_100021], axis = 0)

#promediado

total_promediado_concat = pd.concat([promediado_100001, promediado_100002, promediado_100003,
                                     promediado_100004, promediado_100005, 
                                     promediado_100006, promediado_100023, promediado_08_13,
                                     final_promediado_df_14_19, promediado_100020,
                                     promediado_100021], axis=0)

In [78]:
#social
total_social_concat = pd.concat([social_p_100001, social_p_100002, social_p_100003,
                                 social_p_100004, social_p_100005, social_promediado_1000006, 
                                 social_promediado_100023, social_p_08_13, final_social_p_df_14_19,
                                 social_p_100020, social_100021])

In [79]:
#cost
total_cost_concat = pd.concat([cost_100001, cost_100002, cost_100003,
                               cost_100004, cost_100005, cost_promediado_100006, cost_promediado_100006,
                               cost_08_13, final_cost_df_14_19, cost_100020,
                               cost_100021])

In [80]:
total_promediado_concat.shape

(966, 14)

### Parcela

In [81]:
ha = volum_file[volum_file['CONCEPTO'] == 'HA CULTIVABLE'].iloc[:, 3:].replace(0, np.nan).reset_index(drop = True)
emb = volum_file[volum_file['CONCEPTO'] == 'EMBOLSADOS'].iloc[:, 3:].reset_index(drop = True)
desect_ha_subset = desect_ha.iloc[:, 1:]

In [82]:
original_columns = desect_ha_subset.columns
columns_std  = pd.to_datetime(original_columns, errors = 'raise', dayfirst=True)
desect_ha_subset.columns = columns_std

In [83]:
desect_emb = (desect_ha_subset / ha) * emb *0.5

In [84]:
numerador = emb - desect_emb
denominador = ha - desect_ha_subset
denominador = denominador.replace(0, np.nan)
rac_ha = numerador.divide(denominador)
rac_ha = rac_ha.replace([np.inf, -np.inf], np.nan).fillna(0)
rac_ha[rac_ha < 0] = np.nan
rac_ha = rac_ha.fillna(0)

In [85]:
rac_ha_farms = pd.concat([rac_ha, desect_ha.FINCA], axis = 1)
rac_ha_farms_join = parcela_mo[parcela_mo['LABOR'] == 'PARCELA'][['FINCA', 'ESQUEMA']].merge(rac_ha_farms, on='FINCA', how='inner').iloc[:,1:]
schema_result = vlookup_function(rac_ha_farms_join, esquema_mo, 'VALOR')
schema_result_percent = vlookup_function(rac_ha_farms_join, esquema_mo, 'PORCENTAJE')

In [86]:
parcial_result = abs((desect_ha_subset - ha)).fillna(0)

In [87]:
q_result = parcial_result.multiply(parcela_mo[parcela_mo['LABOR'] == 'PARCELA'].VUELTAS, axis=0)
amount_reesult = (q_result * schema_result)

In [88]:
#AYUDANTE 
schema_result_std = standardize_column_dates(schema_result.iloc[:, 0:-1])
parcela_ay = parcela_mo[parcela_mo['LABOR']=='AYUDANTE']
parcela_plan = parcela_mo[parcela_mo['LABOR']=='PLANTILLA']
matrix_vtas = pd.DataFrame(np.repeat(parcela_ay['VUELTAS'].values[:, np.newaxis], len(ha.columns), axis=1),
                             index=ha.index, columns=ha.columns)
q_initial_result = ((ha - desect_ha_subset).divide(matrix_vtas.replace(0, np.nan))) * schema_result_percent
q_ay = q_initial_result.replace([np.inf, -np.inf], np.nan).fillna(0)
q_ay_std = standardize_column_dates(q_ay.iloc[:, 0:-1])
q_ay_amount = (q_ay_std * 65000)

In [89]:
#PLANTILLA
matrix_vtas_plan = pd.DataFrame(np.repeat(parcela_plan['VUELTAS'].values[:, np.newaxis], len(ha.columns), axis=1),
                             index=ha.index, columns=ha.columns)
q_plan = desect_ha_subset.divide(matrix_vtas_plan.replace(0, np.nan)).fillna(0)
q_plan_std = standardize_column_dates(q_plan.iloc[:, 0:-1])
q_plan_amount = (q_plan_std * 65000)

In [90]:
q_total_results = pd.concat([q_result, q_ay, q_plan], axis = 0)
q_plan_results_amount = pd.concat([amount_reesult, q_ay_amount, q_plan_amount], axis = 0)

In [91]:
q_total_results

,2024-01-06 00:00:00,2024-01-13 00:00:00,2024-01-20 00:00:00,2024-01-27 00:00:00,2024-02-03 00:00:00,2024-02-10 00:00:00,2024-02-17 00:00:00,2024-02-24 00:00:00,2024-03-02 00:00:00,2024-03-09 00:00:00,...,2024-11-02 00:00:00,2024-11-09 00:00:00,2024-11-16 00:00:00,2024-11-23 00:00:00,2024-11-30 00:00:00,2024-12-07 00:00:00,2024-12-14 00:00:00,2024-12-21 00:00:00,2024-12-28 00:00:00,ESQUEMA
0,340.00,340.00,340.00,340.00,340.00,340.00,340.00,340.00,340.00,340.00,...,340.00,340.00,340.00,340.00,340.00,340.00,340.00,340.00,340.00,NaN
1,246.00,246.00,246.00,246.00,246.00,246.00,246.00,246.00,246.00,246.00,...,246.00,246.00,246.00,246.00,246.00,246.00,246.00,246.00,246.00,NaN
2,270.00,272.00,276.00,278.00,282.00,284.00,288.00,290.00,290.00,290.00,...,290.00,290.00,290.00,290.00,290.00,290.00,290.00,290.00,290.00,NaN
3,136.00,136.00,136.00,136.00,136.00,136.00,136.00,136.00,136.00,136.00,...,136.00,136.00,136.00,136.00,136.00,136.00,136.00,136.00,136.00,NaN
4,338.06,338.06,338.06,338.06,338.06,338.06,328.06,328.06,328.06,328.06,...,338.06,338.06,338.06,338.06,338.06,338.06,338.06,338.06,338.06,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN
42,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN
43,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN
44,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN
45,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN

In [92]:
quantity_parcela = calculate_volume_distribution_blocks(q_total_results, volum_distribution_matrix, volum_file_subset, month_columns)

2025-08-28 19:41:31,982 - INFO - Iniciando cálculo de volumen por bloques de 46 filas.
2025-08-28 19:41:32,851 - INFO - Cálculo de matriz de volumen completado correctamente.

In [93]:
labor_parcela = calculate_volume_distribution_blocks(q_plan_results_amount, volum_distribution_matrix, volum_file_subset, month_columns)

2025-08-28 19:41:32,870 - INFO - Iniciando cálculo de volumen por bloques de 46 filas.
2025-08-28 19:41:33,832 - INFO - Cálculo de matriz de volumen completado correctamente.

In [94]:
labor_parcela.columns = [
    col.strftime("%Y-%m") if isinstance(col, pd.Period) else str(col).strip()
    for col in labor_parcela.columns
]

In [95]:
parcela_mo_subset = parcela_mo[['FINCA', 'PROMEDIADO']]
labor_parcela_concat = pd.concat([parcela_mo_subset, labor_parcela], axis = 1)

In [96]:
promediado_parcela = multiply_by_month_promediado(labor_parcela_concat, promediado, month_columns)

2025-08-28 19:41:33,898 - INFO - Columnas después del merge: ['FINCA', 'PROMEDIADO', '2024-01_df1', '2024-02_df1', '2024-03_df1', '2024-04_df1', '2024-05_df1', '2024-06_df1', '2024-07_df1', '2024-08_df1', '2024-09_df1', '2024-10_df1', '2024-11_df1', '2024-12_df1', 'Detalle', '2024-01_df2', '2024-02_df2', '2024-03_df2', '2024-04_df2', '2024-05_df2', '2024-06_df2', '2024-07_df2', '2024-08_df2', '2024-09_df2', '2024-10_df2', '2024-11_df2', '2024-12_df2']
2025-08-28 19:41:33,906 - INFO - Proceso completado exitosamente

In [97]:
social_parcela = social_p_parcela(labor_parcela_concat,promediado_parcela, parcela_mo.PRESTACIONES, month_columns )

In [98]:
cost_parcela = total_cost_parcela(labor_parcela_concat,promediado_parcela, social_parcela, month_columns)
cost_parcela_std = reparar_codificacion(cost_parcela, 'FINCA')

### Labores ciclicas

In [99]:
#Dataframes a utilizar 
ha_cultiv = volum_file[volum_file['CONCEPTO'] == 'HA CULTIVABLE'].iloc[:, 1:].reset_index(drop =True)
emb_ciclic = volum_file[volum_file['CONCEPTO'] == 'EMBOLSADOS'].iloc[:, 1:].reset_index(drop =True)
cortados_ciclic = volum_file[volum_file['CONCEPTO'] == 'CORTADOS'].iloc[:, 1:].reset_index(drop =True)
pre_oper_ciclic = volum_file[volum_file['CONCEPTO'] == 'HA EN PREOPERATIVO'].iloc[:, 1:].reset_index(drop =True)
prod_ciclic = volum_file[volum_file['CONCEPTO'] == 'HA EN PRODUCCIÓN'].iloc[:, 1:].reset_index(drop =True)
curvas_c_std = standardize_column_dates(curvas_c)
ha_cultiv_std = standardize_column_dates(ha_cultiv)
emb_ciclic_std = standardize_column_dates(emb_ciclic)
cortados_ciclic_std = standardize_column_dates(cortados_ciclic)
pre_oper_ciclic_std = standardize_column_dates(pre_oper_ciclic)
prod_ciclic_std = standardize_column_dates(prod_ciclic)

In [100]:
#estandarizar algunos casos detectados con tildes que afectan el proceso
ha_cultiv_std_unicod = reparar_codificacion(ha_cultiv_std, 'FINCA')
emb_ciclic_std_unicod = reparar_codificacion(emb_ciclic_std, 'FINCA')
cortados_ciclic_std_unicod = reparar_codificacion(cortados_ciclic_std, 'FINCA')
pre_oper_ciclic_std_unicod = reparar_codificacion(pre_oper_ciclic_std, 'FINCA')
prod_ciclic_std_unicod = reparar_codificacion(prod_ciclic_std, 'FINCA')

In [101]:
#Filtro por ID a procesar para HA CULTIVABLE
ciclicas_cultiv = ciclicas[ciclicas['ID'].isin([200001, 200002, 400003, 500003, 500004, 600007, 600010,
                                                1000001, 1000002, 1000003, 1000004, 1000005, 1000006, 1000007, 1000008])]
ha_cultiv_merge = ha_cultiv_std_unicod.merge(ciclicas_cultiv[['ID', 'FINCA', 
                                            'CURVA', 'FACTOR']], on = 'FINCA', how = 'outer').sort_values(by = 'ID', 
                                            ascending=True).reset_index(drop =True)
ha_cultiv_merge_curve_c = ha_cultiv_merge.merge(curvas_c_std, on = 'CURVA', how = 'inner')

#APLICAMOS LA MULTIPLICACIÓN DEL DATAFRAME DE HA CULTIVABLE
process_q_ha_cultiv = labores_ciclicas(ha_cultiv_merge_curve_c, 'ID', 'FINCA', 'FACTOR').dropna(axis = 0)
#process_q_ordered = farm_order_process(process_q_ha_cultiv, farm_order, columna_finca='FINCA', columna_id='ID')

In [102]:
#Filtro por ID a procesar para EMBOLSADOS
ciclicas_emb = ciclicas[ciclicas['ID'].isin([200003, 300001, 300002,300003, 300009])]
emb_ciclic_merge = emb_ciclic_std_unicod.merge(ciclicas_emb[['ID', 'FINCA', 
                                            'CURVA', 'FACTOR']], on = 'FINCA', how = 'outer').sort_values(by = 'ID', 
                                            ascending=True).reset_index(drop =True)
emb_ciclic_merge_curve_c = emb_ciclic_merge.merge(curvas_c_std, on = 'CURVA', how = 'inner')

#APLICAMOS LA MULTIPLICACIÓN DEL DATAFRAME DE EMBOLSE
process_q_ciclicas_emb = labores_ciclicas(emb_ciclic_merge_curve_c).dropna(axis = 0)
#process_q_ordered_emb = farm_order_process(process_q_ciclicas_emb, farm_order, columna_finca='FINCA', columna_id='ID')

In [103]:
#Filtro por ID a procesar para CORTADOS
cortados_ciclic_id = ciclicas[ciclicas['ID'].isin([300004, 300007, 300008])]
cortados_ciclic_merge = cortados_ciclic_std_unicod.merge(cortados_ciclic_id[['ID', 'FINCA', 
                                            'CURVA', 'FACTOR']], on = 'FINCA', how = 'outer').sort_values(by = 'ID', 
                                            ascending=True).reset_index(drop =True)
cortados_ciclic_merge_curve_c = cortados_ciclic_merge.merge(curvas_c_std, on = 'CURVA', how = 'inner')

#APLICAMOS LA MULTIPLICACIÓN DEL DATAFRAME DE EMBOLSE
process_q_cortados_ciclic = labores_ciclicas(cortados_ciclic_merge_curve_c).dropna(axis = 0)
#process_q_ordered_cortados = farm_order_process(process_q_cortados_ciclic, farm_order, columna_finca='FINCA', columna_id='ID')

In [104]:
#Filtro por ID a procesar para PREOPERATIVO
pre_oper_ciclic_id = ciclicas[ciclicas['ID'].isin([400002, 400004, 400005, 500002, 500005, 500006, 
                                                600002, 600005,600008, 600009])]
pre_oper_ciclic_merge = pre_oper_ciclic_std_unicod.merge(pre_oper_ciclic_id[['ID', 'FINCA', 
                                            'CURVA', 'FACTOR']], on = 'FINCA', how = 'outer').sort_values(by = 'ID', 
                                            ascending=True).reset_index(drop =True)
pre_oper_ciclic_merge_curve_c = pre_oper_ciclic_merge.merge(curvas_c_std, on = 'CURVA', how = 'inner')

#APLICAMOS LA MULTIPLICACIÓN DEL DATAFRAME DE PREOPERATIVO
process_q_pre_oper_ciclic = labores_ciclicas(pre_oper_ciclic_merge_curve_c).dropna(axis = 0)
#process_q_ordered_pre_oper = farm_order_process(process_q_pre_oper_ciclic, farm_order, columna_finca='FINCA', columna_id='ID')

In [105]:
#Filtro por ID a procesar para PRODUCCIÓN
prod_ciclic_id = ciclicas[ciclicas['ID'].isin([400001, 500001,600001, 600004])]
prod_ciclic_merge = prod_ciclic_std_unicod.merge(prod_ciclic_id[['ID', 'FINCA', 
                                            'CURVA', 'FACTOR']], on = 'FINCA', how = 'outer').sort_values(by = 'ID', 
                                            ascending=True).reset_index(drop =True)
prod_ciclic_merge_curve_c = prod_ciclic_merge.merge(curvas_c_std, on = 'CURVA', how = 'inner')

#APLICAMOS LA MULTIPLICACIÓN DEL DATAFRAME PRODUCCIÓN
process_q_prod_ciclic = labores_ciclicas(prod_ciclic_merge_curve_c).dropna(axis = 0)
#process_q_ordered_prod_ciclic = farm_order_process(process_q_prod_ciclic, farm_order, columna_finca='FINCA', columna_id='ID')

In [106]:
#filtro solamente procesando curva y factor
process_factor_id = ciclicas[ciclicas['ID'].isin([200004, 300005,300006])]

process_factor_merge = process_factor_id.merge(curvas_c_std, on = 'CURVA', how = 'inner')

#nos quedamos con las columnas de interés (fechas)
columnas_fijas = ['ID', 'FINCA', 'MAESTRA', 'CURVA', 'PROMEDIADO', 'PRESTACIONES', 'FACTOR']
columnas_fecha = [col for col in process_factor_merge.columns if col not in columnas_fijas]
#multiplicamos por el factor
process_factor_merge[columnas_fecha] = process_factor_merge[columnas_fecha].multiply(process_factor_merge['FACTOR'], axis=0)
final_columns = ['ID', 'FINCA'] + columnas_fecha

In [107]:
process_factor_merge_filter = process_factor_merge[final_columns]

In [108]:
final_ciclics = pd.concat([process_q_ha_cultiv, process_q_ciclicas_emb, process_q_cortados_ciclic , process_q_pre_oper_ciclic
                           , process_q_prod_ciclic, process_factor_merge_filter],axis = 0)

#final_ciclics_std = reparar_codificacion(final_ciclics, 'FINCA')

In [109]:
final_ciclics_ordered = farm_order_process(final_ciclics, farm_order, 'FINCA', 'ID')

In [110]:
quantity_ciclics = calculate_volume_distribution_blocks_ciclics(final_ciclics_ordered, volum_distribution_matrix, None, month_columns)

2025-08-28 19:41:34,417 - INFO - Iniciando cálculo de volumen por bloques de 46 filas.
2025-08-28 19:41:34,505 - INFO - Cálculo de matriz de volumen completado correctamente.

In [111]:
labor_ciclics = ciclics_labor_calculation(quantity_ciclics, ciclicas)

In [112]:
labor_ciclics_merged = labor_ciclics.merge(ciclicas[['PROMEDIADO', 'ID', 'FINCA']], on = ['ID', 'FINCA'], how = 'inner')

In [113]:
promediado_ciclics = multiply_by_month_promediado_ciclics(labor_ciclics_merged.iloc[:, 1:], promediado, month_columns)
promediado_ciclics_id_concat = pd.concat([promediado_ciclics, labor_ciclics_merged[['ID']]], axis = 1)

In [114]:
social_p_ciclics = multiply_p_social_block_ciclics(labor_ciclics_merged, promediado_ciclics_id_concat,ciclicas,month_columns)

In [115]:
cost_ciclics = total_cost_block(labor_ciclics_merged, promediado_ciclics_id_concat, social_p_ciclics, 'FINCA', 'ID', month_columns)

2025-08-28 19:41:34,630 - INFO - Inicia la función sumar los dataframes de labor y promediados.
2025-08-28 19:41:34,648 - INFO - Suma realizada con éxito.
2025-08-28 19:41:34,648 - INFO - Realizando el merge sobre la columna FINCA y LABOR
2025-08-28 19:41:34,648 - INFO - Proceso completado exitosamente.

## labores fijas

In [116]:
#arreglar URTENTE OJO OJO OJO OJO OJO """"""""""
quantity_fijas_result = quantity_fijas(volum_distribution, f_labor, month_columns, 'SEMANA', mult_cols =('FACTOR',) )
quantity_fijas_result.iloc[:, 2].sum()

np.float64(194793.9167061374)

In [117]:
## FALTA HACER LABORES, PROMEDIADOS, COSTO TOTAL

### LABORES VARIAS

In [118]:
salida_fertilizante_std = reparar_codificacion(salida_fertilizante,'FINCA', aplicar_fix_cienaga=True)
salida_fertilizante_std_sacos = salida_fertilizante_std[salida_fertilizante_std['UNIDAD'] =='SAC']
salida_fertilizante_std_yeso = salida_fertilizante_std[salida_fertilizante_std['UNIDAD'] =='SACO'].reset_index(drop =True)
salida_fertilizante_std_compost = salida_fertilizante_std[salida_fertilizante_std['UNIDAD'] =='BULTO'].reset_index(drop =True)

In [143]:

factor_800001 = other_labors[other_labors['ID']== 800001].FACTOR
factor_800002 = other_labors[other_labors['ID']== 800002].FACTOR
factor_800003 = other_labors[other_labors['ID']== 800003].FACTOR
factor_800004 = other_labors[other_labors['ID']== 800004].reset_index().FACTOR
factor_800005 = other_labors[other_labors['ID']== 800005].reset_index().FACTOR
factor_800006 = other_labors[other_labors['ID']== 800006].reset_index().FACTOR
factor_800008 = other_labors[other_labors['ID']== 800008].reset_index().FACTOR
factor_800009 = other_labors[other_labors['ID']== 800009].reset_index().FACTOR
factor_800010 = other_labors[other_labors['ID']== 800010].FACTOR



factor_1000012 = other_labors[other_labors['ID']== 1000012].FACTOR
factor_1000013 = other_labors[other_labors['ID']== 1000013].FACTOR
factor_1000014 = other_labors[other_labors['ID']== 1000014].FACTOR
factor_1000015 = other_labors[other_labors['ID']== 1000015].FACTOR
factor_1000016 = other_labors[other_labors['ID']== 1000016].FACTOR

In [120]:
def multiply_mat_factor(df: pd.DataFrame, factor, start_col: int = 2) -> pd.DataFrame:
    out = df.copy(deep=True)
    out.iloc[:, start_col:] = out.iloc[:, start_col:].multiply(factor, axis=0)
    return out

In [121]:

factor_800001_quantity = quantity_other_labors(pre_oper_ciclic, volum_distribution, month_columns, factor_800001, multiplicar_por_s=True)
factor_800002_quantity = quantity_other_labors(pre_oper_ciclic, volum_distribution, month_columns, factor_800002, multiplicar_por_s=True)
factor_800003_quantity = quantity_other_labors(ha_cultiv, volum_distribution, month_columns, factor_800003, multiplicar_por_s=True)
factor_800004_quantity = multiply_mat_factor(salida_fertilizante_std_sacos, factor_800004, 2)
factor_800005_quantity = multiply_mat_factor(salida_fertilizante_std_yeso, factor_800005, 2)
factor_800006_quantity = multiply_mat_factor(salida_fertilizante_std_compost, factor_800006, 2)
factor_800008_quantity = quantity_other_labors_800008(volum_distribution, farm_order, month_columns, factor_800008 ,'SEMANA')
factor_800009_quantity = quantity_other_labors(ha_cultiv, volum_distribution, month_columns, factor_800009, multiplicar_por_s=False)

In [154]:

def farm_order_process(df, orden_fincas, columna_finca='FINCA'):
    # Si FINCA está en el índice, lo pasamos a columna
    if columna_finca not in df.columns and df.index.name == columna_finca:
        df = df.reset_index()

    return (df
            .sort_values(
                by=columna_finca,
                key=lambda s: pd.Categorical(s, categories=orden_fincas, ordered=True),
                kind='mergesort'              # orden estable
            )
            .reset_index(drop=True))

In [155]:
test = farm_order_process(factor_800004_quantity, farm_order, columna_finca='FINCA')

In [156]:
test

,UNIDAD,FINCA,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12,FINCA_ORDEN
0,SAC,ENANO,1026.800000,705.500000,977.925000,673.804477,726.473829,674.894188,529.599422,869.952411,805.296240,490.733072,742.819491,732.285620,0
1,SAC,EVA,816.720000,571.950000,707.557500,591.361114,332.380954,492.477780,570.033336,607.980162,503.280161,424.062700,472.257939,447.606351,1
2,SAC,SAMI,1346.874783,963.850000,949.812500,866.271006,778.670567,606.584372,762.318486,718.323599,633.448507,561.032144,659.923306,738.179698,2
3,SAC,VEGA,315.520000,384.200000,357.170000,340.071714,301.557568,291.396389,271.729591,274.515721,363.344091,316.471556,344.988413,264.846212,3
4,SAC,FEDERICA,914.080000,1074.850000,996.480000,817.631957,888.291508,649.260339,661.373405,646.030188,729.610343,676.716622,1063.930966,733.244263,4
5,SAC,NEERLANDIA,607.840000,740.150000,747.027500,347.820245,545.600384,485.038741,375.918664,484.220341,588.430014,570.425201,792.484557,495.405148,5
6,SAC,SAN ANTONIO,663.520000,650.650000,1001.357500,596.022371,606.223242,512.375221,475.069176,596.022371,526.656442,596.022371,610.595045,466.325571,6
7,SAC,MRS,355.706435,363.456429,307.594393,162.785175,164.765530,197.877064,140.209129,132.683780,137.595060,120.009509,236.454379,126.742716,7
8,SAC,DON FUAD,1115.840000,994.400000,913.440000,763.116735,588.427362,705.377300,610.493388,616.009895,659.038646,763.116735,753.922558,735.534203,8
9,SAC,EUFEMIA,1123.120000,1292.700000,1418.495000,1162.527242,1112.887221,1143.422844,1212.482033,1112.346210,998.891829,1041.313902,1107.413410,1093.108293,9
10,SAC,OLGA,222.720000,223.200000,250.920000,180.213281,213.259726,197.221185,195.458708,197.838052,211.056630,181.623263,219.869015,212.907231,10
11,SAC,DON SAID,2611.129477,2711.150000,3103.847500,2375.287457,2037.595987,2355.827270,2431.624104,1917.400718,2524.100647,2393.602926,1920.957630,2536.692532,11
12,SAC,ASUNTINA,1109.152000,1059.058000,980.977140,1010.958854,1044.111974,1064.057280,1273.905600,1362.921120,1202.863200,1331.346720,1187.610336,947.037696,12
13,SAC,PORLAMAR,2554.580000,2037.700000,2744.682500,2032.676518,2084.796429,2105.644393,2244.630822,1963.183304,2183.245149,1958.550423,2391.724791,2288.643191,13
14,SAC,EL MORRO,202.860000,208.250000,257.372500,211.262795,162.901432,262.474933,250.257325,170.537437,244.861215,233.254488,193.954518,225.618484,14
15,SAC,LA PERLA,259.840000,266.000000,292.740000,217.068493,182.571055,237.554663,250.292179,238.297685,226.621629,218.766828,222.375791,256.448645,15
16,SAC,ARACATACA,854.240000,1924.850000,1665.627500,1204.947908,1252.890132,1353.888418,1226.042486,962.040637,1275.263171,1112.898837,1390.324509,1467.671298,16
17,SAC,BOCATOMA,698.250000,645.050000,763.087500,520.556838,541.717685,519.146115,553.003470,576.985763,602.378780,695.486507,592.503718,569.932148,17
18,SAC,JOYA,1068.350000,954.500000,1203.475000,935.756742,787.042345,933.011246,804.888073,752.723639,793.906087,943.993232,1142.812941,740.368904,18
19,SAC,ESMERALDA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,19
20,SAC,NARANJOS,464.000000,475.000000,319.000000,435.442405,391.408903,320.563892,314.692758,400.215603,350.702377,258.525580,473.604773,355.399284,20
21,SAC,YUNQUE,292.320000,349.650000,392.332500,303.036381,217.913802,277.567705,276.478136,322.103838,246.106400,177.735944,386.116017,247.332165,21
22,SAC,DONAMA,635.680000,650.750000,437.030000,447.936635,589.067356,325.950603,480.580785,392.711571,541.696523,357.367529,710.562498,396.638686,22
23,SAC,BURDEOS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23
24,SAC,DON MARCE SUR 2,306.240000,366.300000,408.540000,274.950454,197.717181,227.127611,198.705767,203.277976,221.443242,161.263076,299.047236,222.431828,24
25,SAC,LAS MARGARITAS,743.680000,532.000000,450.240000,381.101798,330.494784,290.835410,536.640905,429.643219,336.071883,285.051751,465.791086,414.770954,25
26,SAC,LA CECILIA,385.120000,266.800000,471.395000,258.790847,214.571682,253.716516,254.876363,238.493525,200.073596,208.772448,245.742569,234.289080,26
27,SAC,JOSEFINA,361.920000,421.200000,393.120000,166.672834,394.491916,498.637782,424.078809,324.469601,315.593533,272.199422,413.230282,394.491916,27
28,SAC,SAN ALFREDO,185.840000,248.400000,284.740000,156.275118,219.333498,189.504143,235.783511,228.106839,175.466799,151.340114,339.418589,263.200198,28
29,SAC,VICTORIA,589.680000,882.700000,1024.205000,972.079342,917.954657,951.728461,1038.327956,850.840048,889.809821,1100.246596,1080.328712,1219.320903,29
30,SAC,CIRCASIA,362.880000,543.200000,630.280000,598.202672,564.895174,585.679053,638.971050,523.593875,547.575274,677.074828,664.817669,750.351325,30
31,SAC,CIENAGA,246.280000,242.050000,292.692500,229.678703,161.573566,153.870641,183.930839,173.315831,181.770262,193.606465,234.375609,226.954498,31
32,SAC,MARIA,225.320000,221.450000,267.782500,237.943950,207.795107,163.082053,211.320202,200.837681,160.948442,154.083782,194.344084,187.015596,32
33,SAC,REMANSO,1632.150000,1667.250000,1487.362500,1143.640056,1336.388380,1233.589273,1048.550882,1236.159251,930.331911,681.044078,1768.144625,935.471866,33
34,SAC,PIEDECUESTA,700.640000,687.050000,864.852500,506.977584,527.586429,505.054092,538.028244,671.848344,696.578957,676.244897,685.587573,663.879590,34
35,SAC,NAUTICA,1828.160000,1674.500000,2069.485000,1538.467490,1579.799452,1434.921949,973.350231,900.596186,950.040683,1194.437765,1204.326665,1141.461519,35
36,SAC,LAS LINAS,1190.218093,1327.070796,1642.392273,1726.005163,1514.214030,1446.095120,1376.368307,1129.986580,874.269889,634.234643,1270.844697,890.778994,36
37,SAC,DON ALI,746.580573,835.699330,1018.227962,992.360175,963.265622,846.252907,790.627943,728.893283,527.347842,380.060588,729.787703,544.218214,37
38,SAC,DR4 DON ALI,36.633803,77.425692,104.003286,115.775881,107.518463,98.125650,106.389899,83.864401,61.853221,44.469636,91.605731,66.661447,38
39,SAC,DON CARLOS,300.746126,281.968086,356.160886,362.689158,308.109722,292.591053,307.232367,242.086210,177.722718,126.890902,272.268387,191.782582,39
40,SAC,EVA NORTE,1969.870998,1977.021744,2465.642696,2254.102558,2041.435759,1908.535201,1894.793432,1614.127613,1331.910780,996.219469,1776.470268,1281.924436,40
41,SAC,DON PEDRO,850.708093,952.256473,1160.242845,1126.250000,1070.919176,964.541204,939.059628,847.811014,644.425614,615.710286,1195.898824,888.043681,41
42,SAC,LA VELA,585.683813,655.596445,798.788043,607.786066,707.143583,634.876217,615.174509,548.090011,414.852983,296.699392,583.167771,431.164142,42
43,SAC,ESPERANZA,526.654925,588.503040,717.040484,705.416356,684.734577,605.836210,594.937204,544.194496,394.769550,261.526366,502.179735,374.486111,43
44,SAC,LINA MARGARITA,401.092000,326.958118,405.900000,217.411741,139.911022,241.294025,292.032843,176.714735,96.630235,46.993030,218.602673,127.627309,44
45,SAC,DON MARCE,1649.655073,1727.651704,2572.383158,166.615467,147.023837,156.421733,108.282235,76.297632,75.272408,51.784473,89.481345,73.493403,45

In [122]:
factor_800010_quantity = salida_fertilizante_std.groupby(by='FINCA', sort=False, as_index=False).sum()
factor_800010_quantity_subset = factor_800010_quantity.loc[:, factor_800010_quantity.columns != 'UNIDAD']

In [144]:
factor_1100001_quantity = build_factor_quantity(curvas_c_mensual, other_labors, 1100001)
factor_1100002_quantity = build_factor_quantity(curvas_c_mensual, other_labors, 1100002)
factor_1100003_quantity = build_factor_quantity(curvas_c_mensual, other_labors, 1100003)
factor_1000009_quantity = build_factor_quantity(curvas_c_mensual, other_labors, 1000009)
factor_1000010_quantity = build_factor_quantity(curvas_c_mensual, other_labors, 1000010)
factor_1000011_quantity = build_factor_quantity(curvas_c_mensual, other_labors, 1000011)
factor_1000012_quantity = quantity_other_labors(ha_cultiv, volum_distribution, month_columns, factor_1000012, multiplicar_por_s=True)
factor_1000013_quantity = quantity_other_labors(ha_cultiv, volum_distribution, month_columns, factor_1000013, multiplicar_por_s=True)
factor_1000014_quantity = quantity_other_labors(ha_cultiv, volum_distribution, month_columns, factor_1000014, multiplicar_por_s=True)
factor_1000015_quantity = quantity_other_labors(ha_cultiv, volum_distribution, month_columns, factor_1000015, multiplicar_por_s=True)
factor_1000016_quantity = quantity_other_labors(ha_cultiv, volum_distribution, month_columns, factor_1000016, multiplicar_por_s=True)